// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { ApprovePostData, ApprovePostErrors, ApprovePostResponses, AutoScheduleData, AutoScheduleErrors, AutoScheduleResponses, CancelPostData, CancelPostErrors, CancelPostResponses, CreateBrandData, CreateBrandErrors, CreateBrandResponses, CreateClipFromUrlData, CreateClipFromUrlErrors, CreateClipFromUrlResponses, CreatePostData, CreatePostErrors, CreatePostResponses, CreateRenderData, CreateRenderErrors, CreateRenderResponses, DeleteClipData, DeleteClipErrors, DeleteClipResponses, DeleteRenderData, DeleteRenderErrors, DeleteRenderResponses, GetClipData, GetClipErrors, GetClipResponses, GetPostData, GetPostErrors, GetPostResponses, GetRenderData, GetRenderErrors, GetRenderResponses, HealthData, HealthResponses, ListAccountsData, ListAccountsResponses, ListBrandsData, ListBrandsErrors, ListBrandsResponses, ListClipsData, ListClipsResponses, ListPostsData, ListPostsErrors, ListPostsResponses, ListRendersData, ListRendersErrors, ListRendersResponses, NextSlotData, NextSlotErrors, NextSlotResponses, RemedyPostData, RemedyPostErrors, RemedyPostResponses, RetryClipData, RetryClipErrors, RetryClipResponses, RetryRenderData, RetryRenderErrors, RetryRenderResponses, StatusData, StatusResponses, SyncAccountsData, SyncAccountsResponses, UpdateAccountData, UpdateAccountErrors, UpdateAccountResponses, UpdateBrandData, UpdateBrandErrors, UpdateBrandResponses, UpdateClipData, UpdateClipErrors, UpdateClipResponses, UpdatePostData, UpdatePostErrors, UpdatePostResponses, UploadBrandLogoData, UploadBrandLogoErrors, UploadBrandLogoResponses, UploadClipData, UploadClipResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Clips
 */
export const listClips = <ThrowOnError extends boolean = false>(options?: Options<ListClipsData, ThrowOnError>): RequestResult<ListClipsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListClipsResponses, unknown, ThrowOnError>({ url: '/api/clips', ...options });

/**
 * Upload Clip
 *
 * Multipart upload, streamed to raw/. The clip is UPLOADING while the bytes arrive, then PROBING.
 */
export const uploadClip = <ThrowOnError extends boolean = false>(options: Options<UploadClipData, ThrowOnError>): RequestResult<UploadClipResponses, unknown, ThrowOnError> => (options.client ?? client).post<UploadClipResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/clips',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Create Clip From Url
 */
export const createClipFromUrl = <ThrowOnError extends boolean = false>(options: Options<CreateClipFromUrlData, ThrowOnError>): RequestResult<CreateClipFromUrlResponses, CreateClipFromUrlErrors, ThrowOnError> => (options.client ?? client).post<CreateClipFromUrlResponses, CreateClipFromUrlErrors, ThrowOnError>({
    url: '/api/clips/from-url',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Clip
 *
 * Only READY/FAILED clips with no renders (delete the renders first). Files go too.
 */
export const deleteClip = <ThrowOnError extends boolean = false>(options: Options<DeleteClipData, ThrowOnError>): RequestResult<DeleteClipResponses, DeleteClipErrors, ThrowOnError> => (options.client ?? client).delete<DeleteClipResponses, DeleteClipErrors, ThrowOnError>({ url: '/api/clips/{clip_id}', ...options });

/**
 * Get Clip
 */
export const getClip = <ThrowOnError extends boolean = false>(options: Options<GetClipData, ThrowOnError>): RequestResult<GetClipResponses, GetClipErrors, ThrowOnError> => (options.client ?? client).get<GetClipResponses, GetClipErrors, ThrowOnError>({ url: '/api/clips/{clip_id}', ...options });

/**
 * Update Clip
 */
export const updateClip = <ThrowOnError extends boolean = false>(options: Options<UpdateClipData, ThrowOnError>): RequestResult<UpdateClipResponses, UpdateClipErrors, ThrowOnError> => (options.client ?? client).patch<UpdateClipResponses, UpdateClipErrors, ThrowOnError>({
    url: '/api/clips/{clip_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retry Clip
 *
 * FAILED -> PROBING again if the bytes are here, else DOWNLOADING again (url clips).
 */
export const retryClip = <ThrowOnError extends boolean = false>(options: Options<RetryClipData, ThrowOnError>): RequestResult<RetryClipResponses, RetryClipErrors, ThrowOnError> => (options.client ?? client).post<RetryClipResponses, RetryClipErrors, ThrowOnError>({ url: '/api/clips/{clip_id}/retry', ...options });

/**
 * List Brands
 */
export const listBrands = <ThrowOnError extends boolean = false>(options?: Options<ListBrandsData, ThrowOnError>): RequestResult<ListBrandsResponses, ListBrandsErrors, ThrowOnError> => (options?.client ?? client).get<ListBrandsResponses, ListBrandsErrors, ThrowOnError>({ url: '/api/brands', ...options });

/**
 * Create Brand
 */
export const createBrand = <ThrowOnError extends boolean = false>(options: Options<CreateBrandData, ThrowOnError>): RequestResult<CreateBrandResponses, CreateBrandErrors, ThrowOnError> => (options.client ?? client).post<CreateBrandResponses, CreateBrandErrors, ThrowOnError>({
    url: '/api/brands',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Brand
 */
export const updateBrand = <ThrowOnError extends boolean = false>(options: Options<UpdateBrandData, ThrowOnError>): RequestResult<UpdateBrandResponses, UpdateBrandErrors, ThrowOnError> => (options.client ?? client).patch<UpdateBrandResponses, UpdateBrandErrors, ThrowOnError>({
    url: '/api/brands/{brand_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload Brand Logo
 *
 * A PNG with transparency. Stored under a new name each time, so browsers never show a stale logo.
 */
export const uploadBrandLogo = <ThrowOnError extends boolean = false>(options: Options<UploadBrandLogoData, ThrowOnError>): RequestResult<UploadBrandLogoResponses, UploadBrandLogoErrors, ThrowOnError> => (options.client ?? client).post<UploadBrandLogoResponses, UploadBrandLogoErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/brands/{brand_id}/logo',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * List Renders
 *
 * unscheduled: renders with no post other than CANCELLED ones.
 */
export const listRenders = <ThrowOnError extends boolean = false>(options?: Options<ListRendersData, ThrowOnError>): RequestResult<ListRendersResponses, ListRendersErrors, ThrowOnError> => (options?.client ?? client).get<ListRendersResponses, ListRendersErrors, ThrowOnError>({ url: '/api/renders', ...options });

/**
 * Create Render
 */
export const createRender = <ThrowOnError extends boolean = false>(options: Options<CreateRenderData, ThrowOnError>): RequestResult<CreateRenderResponses, CreateRenderErrors, ThrowOnError> => (options.client ?? client).post<CreateRenderResponses, CreateRenderErrors, ThrowOnError>({
    url: '/api/renders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Render
 *
 * Not while RENDERING, and not once any post refers to it. Files go too.
 */
export const deleteRender = <ThrowOnError extends boolean = false>(options: Options<DeleteRenderData, ThrowOnError>): RequestResult<DeleteRenderResponses, DeleteRenderErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRenderResponses, DeleteRenderErrors, ThrowOnError>({ url: '/api/renders/{render_id}', ...options });

/**
 * Get Render
 */
export const getRender = <ThrowOnError extends boolean = false>(options: Options<GetRenderData, ThrowOnError>): RequestResult<GetRenderResponses, GetRenderErrors, ThrowOnError> => (options.client ?? client).get<GetRenderResponses, GetRenderErrors, ThrowOnError>({ url: '/api/renders/{render_id}', ...options });

/**
 * Retry Render
 */
export const retryRender = <ThrowOnError extends boolean = false>(options: Options<RetryRenderData, ThrowOnError>): RequestResult<RetryRenderResponses, RetryRenderErrors, ThrowOnError> => (options.client ?? client).post<RetryRenderResponses, RetryRenderErrors, ThrowOnError>({ url: '/api/renders/{render_id}/retry', ...options });

/**
 * List Accounts
 */
export const listAccounts = <ThrowOnError extends boolean = false>(options?: Options<ListAccountsData, ThrowOnError>): RequestResult<ListAccountsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListAccountsResponses, unknown, ThrowOnError>({ url: '/api/accounts', ...options });

/**
 * Sync Accounts
 *
 * Pull GET /v1/accounts from Zernio (read-only) and upsert Instagram accounts by zernio_account_id.
 */
export const syncAccounts = <ThrowOnError extends boolean = false>(options?: Options<SyncAccountsData, ThrowOnError>): RequestResult<SyncAccountsResponses, unknown, ThrowOnError> => (options?.client ?? client).post<SyncAccountsResponses, unknown, ThrowOnError>({ url: '/api/accounts/sync', ...options });

/**
 * Update Account
 */
export const updateAccount = <ThrowOnError extends boolean = false>(options: Options<UpdateAccountData, ThrowOnError>): RequestResult<UpdateAccountResponses, UpdateAccountErrors, ThrowOnError> => (options.client ?? client).patch<UpdateAccountResponses, UpdateAccountErrors, ThrowOnError>({
    url: '/api/accounts/{account_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Next Slot
 */
export const nextSlot = <ThrowOnError extends boolean = false>(options: Options<NextSlotData, ThrowOnError>): RequestResult<NextSlotResponses, NextSlotErrors, ThrowOnError> => (options.client ?? client).get<NextSlotResponses, NextSlotErrors, ThrowOnError>({ url: '/api/accounts/{account_id}/next-slot', ...options });

/**
 * List Posts
 *
 * Sorted by scheduled_for. from/to filter on coalesce(published_at, scheduled_for).
 */
export const listPosts = <ThrowOnError extends boolean = false>(options?: Options<ListPostsData, ThrowOnError>): RequestResult<ListPostsResponses, ListPostsErrors, ThrowOnError> => (options?.client ?? client).get<ListPostsResponses, ListPostsErrors, ThrowOnError>({ url: '/api/posts', ...options });

/**
 * Create Post
 */
export const createPost = <ThrowOnError extends boolean = false>(options: Options<CreatePostData, ThrowOnError>): RequestResult<CreatePostResponses, CreatePostErrors, ThrowOnError> => (options.client ?? client).post<CreatePostResponses, CreatePostErrors, ThrowOnError>({
    url: '/api/posts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Post
 */
export const getPost = <ThrowOnError extends boolean = false>(options: Options<GetPostData, ThrowOnError>): RequestResult<GetPostResponses, GetPostErrors, ThrowOnError> => (options.client ?? client).get<GetPostResponses, GetPostErrors, ThrowOnError>({ url: '/api/posts/{post_id}', ...options });

/**
 * Update Post
 */
export const updatePost = <ThrowOnError extends boolean = false>(options: Options<UpdatePostData, ThrowOnError>): RequestResult<UpdatePostResponses, UpdatePostErrors, ThrowOnError> => (options.client ?? client).patch<UpdatePostResponses, UpdatePostErrors, ThrowOnError>({
    url: '/api/posts/{post_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Auto Schedule
 */
export const autoSchedule = <ThrowOnError extends boolean = false>(options: Options<AutoScheduleData, ThrowOnError>): RequestResult<AutoScheduleResponses, AutoScheduleErrors, ThrowOnError> => (options.client ?? client).post<AutoScheduleResponses, AutoScheduleErrors, ThrowOnError>({
    url: '/api/posts/auto-schedule',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Approve Post
 */
export const approvePost = <ThrowOnError extends boolean = false>(options: Options<ApprovePostData, ThrowOnError>): RequestResult<ApprovePostResponses, ApprovePostErrors, ThrowOnError> => (options.client ?? client).post<ApprovePostResponses, ApprovePostErrors, ThrowOnError>({ url: '/api/posts/{post_id}/approve', ...options });

/**
 * Cancel Post
 */
export const cancelPost = <ThrowOnError extends boolean = false>(options: Options<CancelPostData, ThrowOnError>): RequestResult<CancelPostResponses, CancelPostErrors, ThrowOnError> => (options.client ?? client).post<CancelPostResponses, CancelPostErrors, ThrowOnError>({ url: '/api/posts/{post_id}/cancel', ...options });

/**
 * Remedy Post
 *
 * FAILED / DEAD_LETTER only (409 {"code": "STATE_CONFLICT"} otherwise). See docs/PLAN.md section 4.
 */
export const remedyPost = <ThrowOnError extends boolean = false>(options: Options<RemedyPostData, ThrowOnError>): RequestResult<RemedyPostResponses, RemedyPostErrors, ThrowOnError> => (options.client ?? client).post<RemedyPostResponses, RemedyPostErrors, ThrowOnError>({
    url: '/api/posts/{post_id}/remedy',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Status
 */
export const status = <ThrowOnError extends boolean = false>(options?: Options<StatusData, ThrowOnError>): RequestResult<StatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<StatusResponses, unknown, ThrowOnError>({ url: '/api/status', ...options });
