// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateBrandData, CreateBrandErrors, CreateBrandResponses, CreateClipFromUrlData, CreateClipFromUrlErrors, CreateClipFromUrlResponses, CreateRenderData, CreateRenderErrors, CreateRenderResponses, DeleteClipData, DeleteClipErrors, DeleteClipResponses, DeleteRenderData, DeleteRenderErrors, DeleteRenderResponses, GetClipData, GetClipErrors, GetClipResponses, GetRenderData, GetRenderErrors, GetRenderResponses, HealthData, HealthResponses, ListBrandsData, ListBrandsErrors, ListBrandsResponses, ListClipsData, ListClipsResponses, ListRendersData, ListRendersErrors, ListRendersResponses, RetryClipData, RetryClipErrors, RetryClipResponses, RetryRenderData, RetryRenderErrors, RetryRenderResponses, StatusData, StatusResponses, UpdateBrandData, UpdateBrandErrors, UpdateBrandResponses, UpdateClipData, UpdateClipErrors, UpdateClipResponses, UploadBrandLogoData, UploadBrandLogoErrors, UploadBrandLogoResponses, UploadClipData, UploadClipResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Clips
 */
export const listClips = <ThrowOnError extends boolean = false>(options?: Options<ListClipsData, ThrowOnError>): RequestResult<ListClipsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListClipsResponses, unknown, ThrowOnError>({ url: '/api/clips', ...options });

/**
 * Upload Clip
 *
 * Multipart upload, streamed to raw/. The clip is UPLOADING while the bytes arrive, then PROBING.
 */
export const uploadClip = <ThrowOnError extends boolean = false>(options: Options<UploadClipData, ThrowOnError>): RequestResult<UploadClipResponses, unknown, ThrowOnError> => (options.client ?? client).post<UploadClipResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/clips',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Create Clip From Url
 */
export const createClipFromUrl = <ThrowOnError extends boolean = false>(options: Options<CreateClipFromUrlData, ThrowOnError>): RequestResult<CreateClipFromUrlResponses, CreateClipFromUrlErrors, ThrowOnError> => (options.client ?? client).post<CreateClipFromUrlResponses, CreateClipFromUrlErrors, ThrowOnError>({
    url: '/api/clips/from-url',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Clip
 *
 * Only READY/FAILED clips with no renders (delete the renders first). Files go too.
 */
export const deleteClip = <ThrowOnError extends boolean = false>(options: Options<DeleteClipData, ThrowOnError>): RequestResult<DeleteClipResponses, DeleteClipErrors, ThrowOnError> => (options.client ?? client).delete<DeleteClipResponses, DeleteClipErrors, ThrowOnError>({ url: '/api/clips/{clip_id}', ...options });

/**
 * Get Clip
 */
export const getClip = <ThrowOnError extends boolean = false>(options: Options<GetClipData, ThrowOnError>): RequestResult<GetClipResponses, GetClipErrors, ThrowOnError> => (options.client ?? client).get<GetClipResponses, GetClipErrors, ThrowOnError>({ url: '/api/clips/{clip_id}', ...options });

/**
 * Update Clip
 */
export const updateClip = <ThrowOnError extends boolean = false>(options: Options<UpdateClipData, ThrowOnError>): RequestResult<UpdateClipResponses, UpdateClipErrors, ThrowOnError> => (options.client ?? client).patch<UpdateClipResponses, UpdateClipErrors, ThrowOnError>({
    url: '/api/clips/{clip_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retry Clip
 *
 * FAILED -> PROBING again if the bytes are here, else DOWNLOADING again (url clips).
 */
export const retryClip = <ThrowOnError extends boolean = false>(options: Options<RetryClipData, ThrowOnError>): RequestResult<RetryClipResponses, RetryClipErrors, ThrowOnError> => (options.client ?? client).post<RetryClipResponses, RetryClipErrors, ThrowOnError>({ url: '/api/clips/{clip_id}/retry', ...options });

/**
 * List Brands
 */
export const listBrands = <ThrowOnError extends boolean = false>(options?: Options<ListBrandsData, ThrowOnError>): RequestResult<ListBrandsResponses, ListBrandsErrors, ThrowOnError> => (options?.client ?? client).get<ListBrandsResponses, ListBrandsErrors, ThrowOnError>({ url: '/api/brands', ...options });

/**
 * Create Brand
 */
export const createBrand = <ThrowOnError extends boolean = false>(options: Options<CreateBrandData, ThrowOnError>): RequestResult<CreateBrandResponses, CreateBrandErrors, ThrowOnError> => (options.client ?? client).post<CreateBrandResponses, CreateBrandErrors, ThrowOnError>({
    url: '/api/brands',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Brand
 */
export const updateBrand = <ThrowOnError extends boolean = false>(options: Options<UpdateBrandData, ThrowOnError>): RequestResult<UpdateBrandResponses, UpdateBrandErrors, ThrowOnError> => (options.client ?? client).patch<UpdateBrandResponses, UpdateBrandErrors, ThrowOnError>({
    url: '/api/brands/{brand_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload Brand Logo
 *
 * A PNG with transparency. Stored under a new name each time, so browsers never show a stale logo.
 */
export const uploadBrandLogo = <ThrowOnError extends boolean = false>(options: Options<UploadBrandLogoData, ThrowOnError>): RequestResult<UploadBrandLogoResponses, UploadBrandLogoErrors, ThrowOnError> => (options.client ?? client).post<UploadBrandLogoResponses, UploadBrandLogoErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/brands/{brand_id}/logo',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * List Renders
 *
 * unscheduled: renders with no post other than CANCELLED ones.
 */
export const listRenders = <ThrowOnError extends boolean = false>(options?: Options<ListRendersData, ThrowOnError>): RequestResult<ListRendersResponses, ListRendersErrors, ThrowOnError> => (options?.client ?? client).get<ListRendersResponses, ListRendersErrors, ThrowOnError>({ url: '/api/renders', ...options });

/**
 * Create Render
 */
export const createRender = <ThrowOnError extends boolean = false>(options: Options<CreateRenderData, ThrowOnError>): RequestResult<CreateRenderResponses, CreateRenderErrors, ThrowOnError> => (options.client ?? client).post<CreateRenderResponses, CreateRenderErrors, ThrowOnError>({
    url: '/api/renders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Render
 *
 * Not while RENDERING, and not once any post refers to it. Files go too.
 */
export const deleteRender = <ThrowOnError extends boolean = false>(options: Options<DeleteRenderData, ThrowOnError>): RequestResult<DeleteRenderResponses, DeleteRenderErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRenderResponses, DeleteRenderErrors, ThrowOnError>({ url: '/api/renders/{render_id}', ...options });

/**
 * Get Render
 */
export const getRender = <ThrowOnError extends boolean = false>(options: Options<GetRenderData, ThrowOnError>): RequestResult<GetRenderResponses, GetRenderErrors, ThrowOnError> => (options.client ?? client).get<GetRenderResponses, GetRenderErrors, ThrowOnError>({ url: '/api/renders/{render_id}', ...options });

/**
 * Retry Render
 */
export const retryRender = <ThrowOnError extends boolean = false>(options: Options<RetryRenderData, ThrowOnError>): RequestResult<RetryRenderResponses, RetryRenderErrors, ThrowOnError> => (options.client ?? client).post<RetryRenderResponses, RetryRenderErrors, ThrowOnError>({ url: '/api/renders/{render_id}/retry', ...options });

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Status
 */
export const status = <ThrowOnError extends boolean = false>(options?: Options<StatusData, ThrowOnError>): RequestResult<StatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<StatusResponses, unknown, ThrowOnError>({ url: '/api/status', ...options });
