// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountOut
 */
export type AccountOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Zernio Account Id
     */
    zernio_account_id: string;
    /**
     * Zernio Profile Id
     */
    zernio_profile_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Connection Status
     */
    connection_status: 'connected' | 'disconnected';
    posting_slots: PostingSlots;
    /**
     * Daily Cap
     */
    daily_cap: number;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Min Gap Minutes
     */
    min_gap_minutes: number;
    /**
     * Connected At
     */
    connected_at: string;
    /**
     * Last Publish At
     */
    last_publish_at: string | null;
    /**
     * Disabled At
     */
    disabled_at: string | null;
    /**
     * Today Count
     */
    today_count?: number;
    quota?: Quota | null;
    /**
     * Next Post At
     */
    next_post_at?: string | null;
};

/**
 * AccountPatch
 */
export type AccountPatch = {
    posting_slots?: PostingSlots;
    /**
     * Daily Cap
     */
    daily_cap?: number;
    /**
     * Timezone
     */
    timezone?: string;
    /**
     * Min Gap Minutes
     */
    min_gap_minutes?: number;
    /**
     * Disabled
     */
    disabled?: boolean;
};

/**
 * AutoScheduleIn
 */
export type AutoScheduleIn = {
    /**
     * Render Ids
     */
    render_ids: Array<number>;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Rights Override
     */
    rights_override?: boolean;
};

/**
 * AutoScheduleOut
 */
export type AutoScheduleOut = {
    /**
     * Placed
     */
    placed: Array<Placed>;
    /**
     * Unplaced
     */
    unplaced: Array<Unplaced>;
};

/**
 * Body_upload_brand_logo
 */
export type BodyUploadBrandLogo = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BrandCreate
 */
export type BrandCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template?: string | null;
    /**
     * Link
     */
    link?: string | null;
    /**
     * Auto Approve
     */
    auto_approve?: boolean;
    default_overlay_config?: OverlayConfig | null;
};

/**
 * BrandOut
 */
export type BrandOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template: string | null;
    /**
     * Link
     */
    link: string | null;
    /**
     * Auto Approve
     */
    auto_approve: boolean;
    default_overlay_config: OverlayConfig;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Archived At
     */
    archived_at: string | null;
    /**
     * Logo Url
     */
    readonly logo_url: string | null;
};

/**
 * BrandPatch
 */
export type BrandPatch = {
    /**
     * Name
     */
    name?: string;
    /**
     * Caption Template
     */
    caption_template?: string | null;
    /**
     * Link
     */
    link?: string | null;
    /**
     * Auto Approve
     */
    auto_approve?: boolean;
    default_overlay_config?: OverlayConfig;
    /**
     * Archived
     */
    archived?: boolean;
};

/**
 * ClipFromUrl
 */
export type ClipFromUrl = {
    /**
     * Url
     */
    url: string;
    /**
     * Rights Status
     */
    rights_status: 'permission_granted' | 'none' | 'own_content';
    /**
     * Source Creator Handle
     */
    source_creator_handle?: string | null;
};

/**
 * ClipOut
 */
export type ClipOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Origin
     */
    origin: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Detail
     */
    error_detail: string | null;
    /**
     * Source Url
     */
    source_url: string | null;
    /**
     * Original Filename
     */
    original_filename: string | null;
    /**
     * Platform
     */
    platform: string | null;
    /**
     * Source Creator Handle
     */
    source_creator_handle: string | null;
    /**
     * Rights Status
     */
    rights_status: 'permission_granted' | 'none' | 'own_content';
    /**
     * Has Watermark
     */
    has_watermark: boolean | null;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Width
     */
    width: number | null;
    /**
     * Height
     */
    height: number | null;
    /**
     * Fps
     */
    fps: number | null;
    /**
     * Video Codec
     */
    video_codec: string | null;
    /**
     * Color Transfer
     */
    color_transfer: string | null;
    /**
     * Has Audio
     */
    has_audio: boolean | null;
    /**
     * Uploaded At
     */
    uploaded_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Raw Url
     */
    readonly raw_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * ClipPatch
 */
export type ClipPatch = {
    /**
     * Rights Status
     */
    rights_status?: 'permission_granted' | 'none' | 'own_content';
    /**
     * Source Creator Handle
     */
    source_creator_handle?: string | null;
    /**
     * Has Watermark
     */
    has_watermark?: boolean | null;
};

/**
 * CropConfig
 *
 * Crop rectangle as fractions of the source frame (after autorotate).
 */
export type CropConfig = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * W
     */
    w: number;
    /**
     * H
     */
    h: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status: string;
};

/**
 * NextSlot
 */
export type NextSlot = {
    /**
     * Scheduled For
     */
    scheduled_for: string | null;
};

/**
 * OverlayConfig
 *
 * Logo box as fractions of the 1080x1920 output: top-left x, y and width (height follows the logo,
 * so only y < 1 is checked here).
 */
export type OverlayConfig = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * W
     */
    w: number;
    /**
     * Opacity
     */
    opacity?: number;
};

/**
 * Placed
 */
export type Placed = {
    /**
     * Render Id
     */
    render_id: number;
    post: PostOut;
};

/**
 * PostCreate
 */
export type PostCreate = {
    /**
     * Render Id
     */
    render_id: number;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Scheduled For
     */
    scheduled_for: string;
    /**
     * Caption
     */
    caption?: string | null;
    /**
     * Rights Override
     */
    rights_override?: boolean;
};

/**
 * PostOut
 */
export type PostOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Render Id
     */
    render_id: number;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Account Username
     */
    account_username: string;
    /**
     * Caption
     */
    caption: string;
    /**
     * Scheduled For
     */
    scheduled_for: string;
    /**
     * Status
     */
    status: 'DRAFT' | 'SCHEDULED' | 'PUBLISHING' | 'PUBLISHED' | 'FAILED' | 'DEAD_LETTER' | 'CANCELLED';
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Detail
     */
    error_detail: {
        [key: string]: unknown;
    } | null;
    /**
     * Cause
     */
    cause: string | null;
    remedy: Remedy | null;
    /**
     * Attempt Count
     */
    attempt_count: number;
    /**
     * Zernio Post Id
     */
    zernio_post_id: string | null;
    /**
     * Permalink
     */
    permalink: string | null;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    render: PostRender;
};

/**
 * PostPatch
 */
export type PostPatch = {
    /**
     * Scheduled For
     */
    scheduled_for?: string;
    /**
     * Caption
     */
    caption?: string;
};

/**
 * PostRender
 */
export type PostRender = {
    /**
     * Id
     */
    id: number;
    /**
     * Clip Id
     */
    clip_id: number;
    /**
     * Clip Name
     */
    clip_name: string | null;
    /**
     * Brand Id
     */
    brand_id: number | null;
    /**
     * Brand Name
     */
    brand_name: string | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Thumbnail Url
     */
    thumbnail_url: string | null;
    /**
     * Output Url
     */
    output_url: string | null;
};

/**
 * PostingSlots
 */
export type PostingSlots = {
    /**
     * Times
     */
    times?: Array<string>;
};

/**
 * Quota
 */
export type Quota = {
    /**
     * Used
     */
    used: number;
    /**
     * Total
     */
    total: number;
    /**
     * Duration S
     */
    duration_s: number;
};

/**
 * Remedy
 */
export type Remedy = {
    /**
     * Action
     */
    action: 'reconnect' | 'rerender' | 'retry' | 'auto';
    /**
     * Label
     */
    label: string;
};

/**
 * RemedyIn
 */
export type RemedyIn = {
    /**
     * Action
     */
    action?: 'reconnect' | 'rerender' | 'retry' | null;
};

/**
 * RenderCreate
 */
export type RenderCreate = {
    /**
     * Clip Id
     */
    clip_id: number;
    /**
     * Brand Id
     */
    brand_id?: number | null;
    overlay_config?: OverlayConfig | null;
    crop_config?: CropConfig | null;
    /**
     * Caption
     */
    caption?: string | null;
};

/**
 * RenderDetail
 */
export type RenderDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Ffmpeg Log
     */
    ffmpeg_log: string | null;
    /**
     * Output Url
     */
    readonly output_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * RenderOut
 */
export type RenderOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Output Url
     */
    readonly output_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * SystemStatus
 */
export type SystemStatus = {
    /**
     * Db
     */
    db: boolean;
    /**
     * Worker Alive
     */
    worker_alive: boolean;
    /**
     * Worker Last Heartbeat
     */
    worker_last_heartbeat: string | null;
    /**
     * Jobs
     */
    jobs: {
        [key: string]: number;
    };
    /**
     * Failed Posts
     */
    failed_posts?: number;
    /**
     * Rendering Renders
     */
    rendering_renders?: number;
    /**
     * Scheduled Posts
     */
    scheduled_posts?: number;
};

/**
 * Unplaced
 */
export type Unplaced = {
    /**
     * Render Id
     */
    render_id: number;
    /**
     * Reason
     */
    reason: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * BrandOut
 */
export type BrandOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template: string | null;
    /**
     * Link
     */
    link: string | null;
    /**
     * Auto Approve
     */
    auto_approve: boolean;
    default_overlay_config: OverlayConfig;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Archived At
     */
    archived_at: string | null;
};

/**
 * ClipOut
 */
export type ClipOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Origin
     */
    origin: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Detail
     */
    error_detail: string | null;
    /**
     * Source Url
     */
    source_url: string | null;
    /**
     * Original Filename
     */
    original_filename: string | null;
    /**
     * Platform
     */
    platform: string | null;
    /**
     * Source Creator Handle
     */
    source_creator_handle: string | null;
    /**
     * Rights Status
     */
    rights_status: 'permission_granted' | 'none' | 'own_content';
    /**
     * Has Watermark
     */
    has_watermark: boolean | null;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Width
     */
    width: number | null;
    /**
     * Height
     */
    height: number | null;
    /**
     * Fps
     */
    fps: number | null;
    /**
     * Video Codec
     */
    video_codec: string | null;
    /**
     * Color Transfer
     */
    color_transfer: string | null;
    /**
     * Has Audio
     */
    has_audio: boolean | null;
    /**
     * Uploaded At
     */
    uploaded_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RenderDetail
 */
export type RenderDetailWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Ffmpeg Log
     */
    ffmpeg_log: string | null;
};

/**
 * RenderOut
 */
export type RenderOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

export type ListClipsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/clips';
};

export type ListClipsResponses = {
    /**
     * Response List Clips
     *
     * Successful Response
     */
    200: Array<ClipOut>;
};

export type ListClipsResponse = ListClipsResponses[keyof ListClipsResponses];

export type UploadClipData = {
    body: {
        /**
         * .mp4, .mov or .webm
         */
        file: Blob | File;
        rights_status: 'permission_granted' | 'none' | 'own_content';
        source_creator_handle?: string;
    };
    path?: never;
    query?: never;
    url: '/api/clips';
};

export type UploadClipResponses = {
    /**
     * Successful Response
     */
    201: ClipOut;
};

export type UploadClipResponse = UploadClipResponses[keyof UploadClipResponses];

export type CreateClipFromUrlData = {
    body: ClipFromUrl;
    path?: never;
    query?: never;
    url: '/api/clips/from-url';
};

export type CreateClipFromUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClipFromUrlError = CreateClipFromUrlErrors[keyof CreateClipFromUrlErrors];

export type CreateClipFromUrlResponses = {
    /**
     * Successful Response
     */
    201: ClipOut;
};

export type CreateClipFromUrlResponse = CreateClipFromUrlResponses[keyof CreateClipFromUrlResponses];

export type DeleteClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}';
};

export type DeleteClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClipError = DeleteClipErrors[keyof DeleteClipErrors];

export type DeleteClipResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteClipResponse = DeleteClipResponses[keyof DeleteClipResponses];

export type GetClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}';
};

export type GetClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetClipError = GetClipErrors[keyof GetClipErrors];

export type GetClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type GetClipResponse = GetClipResponses[keyof GetClipResponses];

export type UpdateClipData = {
    body: ClipPatch;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}';
};

export type UpdateClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClipError = UpdateClipErrors[keyof UpdateClipErrors];

export type UpdateClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type UpdateClipResponse = UpdateClipResponses[keyof UpdateClipResponses];

export type RetryClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}/retry';
};

export type RetryClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryClipError = RetryClipErrors[keyof RetryClipErrors];

export type RetryClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type RetryClipResponse = RetryClipResponses[keyof RetryClipResponses];

export type ListBrandsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Archived
         */
        archived?: boolean;
    };
    url: '/api/brands';
};

export type ListBrandsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBrandsError = ListBrandsErrors[keyof ListBrandsErrors];

export type ListBrandsResponses = {
    /**
     * Response List Brands
     *
     * Successful Response
     */
    200: Array<BrandOut>;
};

export type ListBrandsResponse = ListBrandsResponses[keyof ListBrandsResponses];

export type CreateBrandData = {
    body: BrandCreate;
    path?: never;
    query?: never;
    url: '/api/brands';
};

export type CreateBrandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBrandError = CreateBrandErrors[keyof CreateBrandErrors];

export type CreateBrandResponses = {
    /**
     * Successful Response
     */
    201: BrandOut;
};

export type CreateBrandResponse = CreateBrandResponses[keyof CreateBrandResponses];

export type UpdateBrandData = {
    body: BrandPatch;
    path: {
        /**
         * Brand Id
         */
        brand_id: number;
    };
    query?: never;
    url: '/api/brands/{brand_id}';
};

export type UpdateBrandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBrandError = UpdateBrandErrors[keyof UpdateBrandErrors];

export type UpdateBrandResponses = {
    /**
     * Successful Response
     */
    200: BrandOut;
};

export type UpdateBrandResponse = UpdateBrandResponses[keyof UpdateBrandResponses];

export type UploadBrandLogoData = {
    body: BodyUploadBrandLogo;
    path: {
        /**
         * Brand Id
         */
        brand_id: number;
    };
    query?: never;
    url: '/api/brands/{brand_id}/logo';
};

export type UploadBrandLogoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadBrandLogoError = UploadBrandLogoErrors[keyof UploadBrandLogoErrors];

export type UploadBrandLogoResponses = {
    /**
     * Successful Response
     */
    200: BrandOut;
};

export type UploadBrandLogoResponse = UploadBrandLogoResponses[keyof UploadBrandLogoResponses];

export type ListRendersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Clip Id
         */
        clip_id?: number | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Unscheduled
         */
        unscheduled?: boolean;
    };
    url: '/api/renders';
};

export type ListRendersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRendersError = ListRendersErrors[keyof ListRendersErrors];

export type ListRendersResponses = {
    /**
     * Response List Renders
     *
     * Successful Response
     */
    200: Array<RenderOut>;
};

export type ListRendersResponse = ListRendersResponses[keyof ListRendersResponses];

export type CreateRenderData = {
    body: RenderCreate;
    path?: never;
    query?: never;
    url: '/api/renders';
};

export type CreateRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRenderError = CreateRenderErrors[keyof CreateRenderErrors];

export type CreateRenderResponses = {
    /**
     * Successful Response
     */
    201: RenderOut;
};

export type CreateRenderResponse = CreateRenderResponses[keyof CreateRenderResponses];

export type DeleteRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}';
};

export type DeleteRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRenderError = DeleteRenderErrors[keyof DeleteRenderErrors];

export type DeleteRenderResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRenderResponse = DeleteRenderResponses[keyof DeleteRenderResponses];

export type GetRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}';
};

export type GetRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRenderError = GetRenderErrors[keyof GetRenderErrors];

export type GetRenderResponses = {
    /**
     * Successful Response
     */
    200: RenderDetail;
};

export type GetRenderResponse = GetRenderResponses[keyof GetRenderResponses];

export type RetryRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}/retry';
};

export type RetryRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryRenderError = RetryRenderErrors[keyof RetryRenderErrors];

export type RetryRenderResponses = {
    /**
     * Successful Response
     */
    200: RenderOut;
};

export type RetryRenderResponse = RetryRenderResponses[keyof RetryRenderResponses];

export type ListAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts';
};

export type ListAccountsResponses = {
    /**
     * Response List Accounts
     *
     * Successful Response
     */
    200: Array<AccountOut>;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type SyncAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/sync';
};

export type SyncAccountsResponses = {
    /**
     * Response Sync Accounts
     *
     * Successful Response
     */
    200: Array<AccountOut>;
};

export type SyncAccountsResponse = SyncAccountsResponses[keyof SyncAccountsResponses];

export type UpdateAccountData = {
    body: AccountPatch;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/{account_id}';
};

export type UpdateAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountOut;
};

export type UpdateAccountResponse = UpdateAccountResponses[keyof UpdateAccountResponses];

export type NextSlotData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/{account_id}/next-slot';
};

export type NextSlotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NextSlotError = NextSlotErrors[keyof NextSlotErrors];

export type NextSlotResponses = {
    /**
     * Successful Response
     */
    200: NextSlot;
};

export type NextSlotResponse = NextSlotResponses[keyof NextSlotResponses];

export type ListPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * From
         */
        from?: string | null;
        /**
         * To
         */
        to?: string | null;
        /**
         * Account Id
         */
        account_id?: number | null;
        /**
         * Brand Id
         */
        brand_id?: number | null;
        /**
         * Status
         */
        status?: Array<'DRAFT' | 'SCHEDULED' | 'PUBLISHING' | 'PUBLISHED' | 'FAILED' | 'DEAD_LETTER' | 'CANCELLED'> | null;
    };
    url: '/api/posts';
};

export type ListPostsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPostsError = ListPostsErrors[keyof ListPostsErrors];

export type ListPostsResponses = {
    /**
     * Response List Posts
     *
     * Successful Response
     */
    200: Array<PostOut>;
};

export type ListPostsResponse = ListPostsResponses[keyof ListPostsResponses];

export type CreatePostData = {
    body: PostCreate;
    path?: never;
    query?: never;
    url: '/api/posts';
};

export type CreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
    /**
     * Successful Response
     */
    201: PostOut;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type GetPostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}';
};

export type GetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type UpdatePostData = {
    body: PostPatch;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}';
};

export type UpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePostError = UpdatePostErrors[keyof UpdatePostErrors];

export type UpdatePostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type UpdatePostResponse = UpdatePostResponses[keyof UpdatePostResponses];

export type AutoScheduleData = {
    body: AutoScheduleIn;
    path?: never;
    query?: never;
    url: '/api/posts/auto-schedule';
};

export type AutoScheduleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AutoScheduleError = AutoScheduleErrors[keyof AutoScheduleErrors];

export type AutoScheduleResponses = {
    /**
     * Successful Response
     */
    200: AutoScheduleOut;
};

export type AutoScheduleResponse = AutoScheduleResponses[keyof AutoScheduleResponses];

export type ApprovePostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}/approve';
};

export type ApprovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApprovePostError = ApprovePostErrors[keyof ApprovePostErrors];

export type ApprovePostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type ApprovePostResponse = ApprovePostResponses[keyof ApprovePostResponses];

export type CancelPostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}/cancel';
};

export type CancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelPostError = CancelPostErrors[keyof CancelPostErrors];

export type CancelPostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type CancelPostResponse = CancelPostResponses[keyof CancelPostResponses];

export type RemedyPostData = {
    body: RemedyIn;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}/remedy';
};

export type RemedyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemedyPostError = RemedyPostErrors[keyof RemedyPostErrors];

export type RemedyPostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type RemedyPostResponse = RemedyPostResponses[keyof RemedyPostResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type StatusResponses = {
    /**
     * Successful Response
     */
    200: SystemStatus;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];
