// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountOut
 */
export type AccountOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Zernio Account Id
     */
    zernio_account_id: string;
    /**
     * Zernio Profile Id
     */
    zernio_profile_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Connection Status
     */
    connection_status: 'connected' | 'disconnected';
    posting_slots: PostingSlots;
    /**
     * Daily Cap
     */
    daily_cap: number;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Min Gap Minutes
     */
    min_gap_minutes: number;
    /**
     * Connected At
     */
    connected_at: string;
    /**
     * Last Publish At
     */
    last_publish_at: string | null;
    /**
     * Disabled At
     */
    disabled_at: string | null;
    /**
     * Today Count
     */
    today_count?: number;
    quota?: Quota | null;
    /**
     * Next Post At
     */
    next_post_at?: string | null;
};

/**
 * AccountPatch
 */
export type AccountPatch = {
    posting_slots?: PostingSlots;
    /**
     * Daily Cap
     */
    daily_cap?: number;
    /**
     * Timezone
     */
    timezone?: string;
    /**
     * Min Gap Minutes
     */
    min_gap_minutes?: number;
    /**
     * Disabled
     */
    disabled?: boolean;
};

/**
 * AutoScheduleIn
 */
export type AutoScheduleIn = {
    /**
     * Render Ids
     */
    render_ids: Array<number>;
    /**
     * Account Id
     */
    account_id: number;
};

/**
 * AutoScheduleOut
 */
export type AutoScheduleOut = {
    /**
     * Placed
     */
    placed: Array<Placed>;
    /**
     * Unplaced
     */
    unplaced: Array<Unplaced>;
};

/**
 * Body_find_links
 */
export type BodyFindLinks = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_set_render_cover
 */
export type BodySetRenderCover = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_brand_logo
 */
export type BodyUploadBrandLogo = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_cover
 */
export type BodyUploadCover = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * Body_upload_track
 */
export type BodyUploadTrack = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * BotIn
 */
export type BotIn = {
    /**
     * Token
     */
    token: string;
};

/**
 * BotOut
 */
export type BotOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string | null;
    /**
     * Chat Title
     */
    chat_title: string | null;
    /**
     * Alerts
     */
    alerts: boolean;
    /**
     * Health
     */
    health: 'running' | 'waiting' | 'rejected' | 'not_responding';
    /**
     * Pairing
     */
    pairing: boolean;
    /**
     * Last Seen At
     */
    last_seen_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * BotPairing
 */
export type BotPairing = {
    bot: BotOut;
    /**
     * Pair Url
     */
    pair_url: string | null;
    /**
     * Start
     */
    start: string | null;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * BotPatch
 */
export type BotPatch = {
    /**
     * Alerts
     */
    alerts: boolean;
};

/**
 * BotTest
 */
export type BotTest = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Error
     */
    error: string | null;
};

/**
 * BrandCreate
 */
export type BrandCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template?: string | null;
    /**
     * Link
     */
    link?: string | null;
    /**
     * Auto Approve
     */
    auto_approve?: boolean;
    default_overlay_config?: OverlayConfig | null;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * BrandOut
 */
export type BrandOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template: string | null;
    /**
     * Link
     */
    link: string | null;
    /**
     * Auto Approve
     */
    auto_approve: boolean;
    default_overlay_config: OverlayConfig;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Archived At
     */
    archived_at: string | null;
    /**
     * Logo Url
     */
    readonly logo_url: string | null;
};

/**
 * BrandPatch
 */
export type BrandPatch = {
    /**
     * Name
     */
    name?: string;
    /**
     * Caption Template
     */
    caption_template?: string | null;
    /**
     * Link
     */
    link?: string | null;
    /**
     * Auto Approve
     */
    auto_approve?: boolean;
    default_overlay_config?: OverlayConfig;
    /**
     * Archived
     */
    archived?: boolean;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * CaptionCreate
 */
export type CaptionCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Text
     */
    text: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * CaptionOut
 */
export type CaptionOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Text
     */
    text: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CaptionPatch
 */
export type CaptionPatch = {
    /**
     * Name
     */
    name?: string;
    /**
     * Text
     */
    text?: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * ClipFromUrl
 */
export type ClipFromUrl = {
    /**
     * Url
     */
    url: string;
    /**
     * Source Creator Handle
     */
    source_creator_handle?: string | null;
};

/**
 * ClipOut
 */
export type ClipOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Origin
     */
    origin: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Detail
     */
    error_detail: string | null;
    /**
     * Source Url
     */
    source_url: string | null;
    /**
     * Original Filename
     */
    original_filename: string | null;
    /**
     * Platform
     */
    platform: string | null;
    /**
     * Source Creator Handle
     */
    source_creator_handle: string | null;
    /**
     * Has Watermark
     */
    has_watermark: boolean | null;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Width
     */
    width: number | null;
    /**
     * Height
     */
    height: number | null;
    /**
     * Fps
     */
    fps: number | null;
    /**
     * Video Codec
     */
    video_codec: string | null;
    /**
     * Color Transfer
     */
    color_transfer: string | null;
    /**
     * Has Audio
     */
    has_audio: boolean | null;
    /**
     * Uploaded At
     */
    uploaded_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Raw Url
     */
    readonly raw_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * ClipPatch
 */
export type ClipPatch = {
    /**
     * Source Creator Handle
     */
    source_creator_handle?: string | null;
    /**
     * Has Watermark
     */
    has_watermark?: boolean | null;
};

/**
 * ClipsFromUrls
 */
export type ClipsFromUrls = {
    /**
     * Urls
     */
    urls: Array<string>;
};

/**
 * ClipsFromUrlsOut
 */
export type ClipsFromUrlsOut = {
    /**
     * Created
     */
    created: number;
    /**
     * Skipped
     */
    skipped: number;
    /**
     * Ids
     */
    ids: Array<number>;
};

/**
 * CoverOut
 */
export type CoverOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Image Url
     */
    readonly image_url: string;
};

/**
 * CoverPatch
 */
export type CoverPatch = {
    /**
     * Name
     */
    name?: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * Credentials
 */
export type Credentials = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * CropConfig
 *
 * Crop rectangle as fractions of the source frame (after autorotate).
 */
export type CropConfig = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * W
     */
    w: number;
    /**
     * H
     */
    h: number;
};

/**
 * FilterLayer
 */
export type FilterLayer = {
    /**
     * Mode
     */
    mode: 'multiply' | 'screen' | 'overlay' | 'darken' | 'lighten' | 'color-dodge' | 'soft-light' | 'exclusion';
    /**
     * Color
     */
    color: string;
    /**
     * Opacity
     */
    opacity: number;
};

/**
 * FilterOut
 */
export type FilterOut = {
    /**
     * Name
     */
    name: 'Clarendon' | 'Gingham' | 'Moon' | 'Lark' | 'Reyes' | 'Juno' | 'Slumber' | 'Crema' | 'Ludwig' | 'Aden' | 'Valencia' | 'Nashville' | 'Inkwell' | '1977';
    /**
     * Layers
     */
    layers: Array<FilterLayer>;
    /**
     * Css
     */
    css: string;
};

/**
 * FoundLink
 */
export type FoundLink = {
    /**
     * Url
     */
    url: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * In Library
     */
    in_library: boolean;
};

/**
 * FreedSpace
 */
export type FreedSpace = {
    /**
     * Renders
     */
    renders: number;
    /**
     * Bytes
     */
    bytes: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status: string;
};

/**
 * KeyCheck
 */
export type KeyCheck = {
    zernio: ZernioKeyOut;
    /**
     * Accounts
     */
    accounts: Array<string>;
    /**
     * Skipped
     */
    skipped: Array<string>;
    /**
     * Over Limit
     */
    over_limit: Array<string>;
};

/**
 * LinksOut
 */
export type LinksOut = {
    /**
     * Links
     */
    links: Array<FoundLink>;
    /**
     * Repeats
     */
    repeats: number;
    /**
     * Other
     */
    other: Array<string>;
    /**
     * Other Count
     */
    other_count: number;
};

/**
 * Me
 */
export type Me = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    setup: Setup;
    zernio: ZernioKeyOut;
    /**
     * Bots
     */
    bots: Array<BotOut>;
    storage: Storage;
};

/**
 * MusicOut
 */
export type MusicOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string | null;
    /**
     * Artist
     */
    artist: string | null;
    /**
     * Kind
     */
    kind: 'music' | 'original_sound';
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Preview Url
     */
    preview_url: string | null;
    /**
     * Artwork Url
     */
    artwork_url: string | null;
};

/**
 * NextSlot
 */
export type NextSlot = {
    /**
     * Scheduled For
     */
    scheduled_for: string | null;
};

/**
 * OverlayConfig
 *
 * Logo box as fractions of the 1080x1920 output: top-left x, y and width (height follows the logo,
 * so only y < 1 is checked here).
 */
export type OverlayConfig = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * W
     */
    w: number;
    /**
     * Opacity
     */
    opacity?: number;
};

/**
 * PasswordChange
 */
export type PasswordChange = {
    /**
     * Current
     */
    current: string;
    /**
     * New
     */
    new: string;
};

/**
 * Placed
 */
export type Placed = {
    /**
     * Render Id
     */
    render_id: number;
    post: PostOut;
};

/**
 * PostCreate
 */
export type PostCreate = {
    /**
     * Render Id
     */
    render_id: number;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Scheduled For
     */
    scheduled_for: string;
    /**
     * Caption
     */
    caption?: string | null;
    music?: PostMusic | null;
    /**
     * Repost
     */
    repost?: boolean;
};

/**
 * PostMusic
 *
 * Instagram's catalog track a Reel goes out with (Zernio audioConfiguration); title and artist are for show.
 */
export type PostMusic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Artist
     */
    artist?: string | null;
    /**
     * Volume
     */
    volume?: number;
    /**
     * Video Volume
     */
    video_volume?: number;
};

/**
 * PostOut
 */
export type PostOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Render Id
     */
    render_id: number;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Account Username
     */
    account_username: string;
    /**
     * Caption
     */
    caption: string;
    music: PostMusic | null;
    /**
     * Scheduled For
     */
    scheduled_for: string;
    /**
     * Status
     */
    status: 'DRAFT' | 'SCHEDULED' | 'PUBLISHING' | 'PUBLISHED' | 'FAILED' | 'DEAD_LETTER' | 'CANCELLED';
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Detail
     */
    error_detail: {
        [key: string]: unknown;
    } | null;
    /**
     * Cause
     */
    cause: string | null;
    remedy: Remedy | null;
    /**
     * Attempt Count
     */
    attempt_count: number;
    /**
     * Zernio Post Id
     */
    zernio_post_id: string | null;
    /**
     * Permalink
     */
    permalink: string | null;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    render: PostRender;
};

/**
 * PostPatch
 */
export type PostPatch = {
    /**
     * Scheduled For
     */
    scheduled_for?: string;
    /**
     * Caption
     */
    caption?: string;
    music?: PostMusic | null;
};

/**
 * PostRender
 */
export type PostRender = {
    /**
     * Id
     */
    id: number;
    /**
     * Clip Id
     */
    clip_id: number;
    /**
     * Clip Name
     */
    clip_name: string | null;
    /**
     * Brand Id
     */
    brand_id: number | null;
    /**
     * Brand Name
     */
    brand_name: string | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Thumbnail Url
     */
    thumbnail_url: string | null;
    /**
     * Output Url
     */
    output_url: string | null;
};

/**
 * PostingSlots
 */
export type PostingSlots = {
    /**
     * Times
     */
    times?: Array<string>;
};

/**
 * Quota
 */
export type Quota = {
    /**
     * Used
     */
    used: number;
    /**
     * Total
     */
    total: number;
    /**
     * Duration S
     */
    duration_s: number;
};

/**
 * Remedy
 */
export type Remedy = {
    /**
     * Action
     */
    action: 'reconnect' | 'rerender' | 'retry' | 'auto';
    /**
     * Label
     */
    label: string;
};

/**
 * RemedyIn
 */
export type RemedyIn = {
    /**
     * Action
     */
    action?: 'reconnect' | 'rerender' | 'retry' | null;
};

/**
 * RenderCreate
 */
export type RenderCreate = {
    /**
     * Clip Id
     */
    clip_id: number;
    /**
     * Brand Id
     */
    brand_id?: number | null;
    overlay_config?: OverlayConfig | null;
    crop_config?: CropConfig | null;
    /**
     * Filter
     */
    filter?: 'Clarendon' | 'Gingham' | 'Moon' | 'Lark' | 'Reyes' | 'Juno' | 'Slumber' | 'Crema' | 'Ludwig' | 'Aden' | 'Valencia' | 'Nashville' | 'Inkwell' | '1977' | null;
    music?: RenderMusic | null;
    /**
     * Caption
     */
    caption?: string | null;
};

/**
 * RenderDetail
 */
export type RenderDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Filter
     */
    filter: string | null;
    music: RenderMusic | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Ffmpeg Log
     */
    ffmpeg_log: string | null;
    /**
     * Output Url
     */
    readonly output_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
    /**
     * Cover Url
     */
    readonly cover_url: string | null;
};

/**
 * RenderMusic
 *
 * A saved track mixed into a render (renders.music): looped to the clip's length, faded out at its end.
 */
export type RenderMusic = {
    /**
     * Track Id
     */
    track_id: number;
    /**
     * Volume
     */
    volume?: number;
    /**
     * Clip Volume
     */
    clip_volume?: number;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * RenderOut
 */
export type RenderOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Filter
     */
    filter: string | null;
    music: RenderMusic | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Output Url
     */
    readonly output_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
    /**
     * Cover Url
     */
    readonly cover_url: string | null;
};

/**
 * Setup
 */
export type Setup = {
    /**
     * Zernio
     */
    zernio: boolean;
    /**
     * Instagram
     */
    instagram: boolean;
    /**
     * Telegram
     */
    telegram: boolean;
};

/**
 * SignupStatus
 */
export type SignupStatus = {
    /**
     * Open
     */
    open: boolean;
    /**
     * Remaining
     */
    remaining: number;
    /**
     * Max Users
     */
    max_users: number;
};

/**
 * Storage
 */
export type Storage = {
    /**
     * Used Bytes
     */
    used_bytes: number;
    /**
     * Quota Bytes
     */
    quota_bytes: number | null;
};

/**
 * SystemStatus
 */
export type SystemStatus = {
    /**
     * Db
     */
    db: boolean;
    /**
     * Worker Alive
     */
    worker_alive: boolean;
    /**
     * Worker Last Heartbeat
     */
    worker_last_heartbeat: string | null;
    /**
     * Publisher Alive
     */
    publisher_alive: boolean;
    /**
     * Failed Posts
     */
    failed_posts?: number;
    /**
     * Rendering Renders
     */
    rendering_renders?: number;
    /**
     * Scheduled Posts
     */
    scheduled_posts?: number;
    /**
     * Publishing Enabled
     */
    publishing_enabled: boolean;
    /**
     * Publishing Off
     */
    publishing_off?: 'switch' | 'no_key' | 'key_invalid' | null;
    /**
     * Instagram Music
     */
    instagram_music?: boolean;
};

/**
 * TrackOut
 */
export type TrackOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Audio Url
     */
    readonly audio_url: string;
};

/**
 * TrackPatch
 */
export type TrackPatch = {
    /**
     * Name
     */
    name?: string;
    /**
     * Is Default
     */
    is_default?: boolean;
};

/**
 * Unplaced
 */
export type Unplaced = {
    /**
     * Render Id
     */
    render_id: number;
    /**
     * Reason
     */
    reason: string;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ZernioKeyIn
 */
export type ZernioKeyIn = {
    /**
     * Key
     */
    key: string;
};

/**
 * ZernioKeyOut
 */
export type ZernioKeyOut = {
    /**
     * Status
     */
    status: 'none' | 'valid' | 'invalid';
    /**
     * Last4
     */
    last4: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Name
     */
    name: string | null;
    /**
     * Checked At
     */
    checked_at: string | null;
    /**
     * Error
     */
    error: string | null;
};

/**
 * BrandOut
 */
export type BrandOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template: string | null;
    /**
     * Link
     */
    link: string | null;
    /**
     * Auto Approve
     */
    auto_approve: boolean;
    default_overlay_config: OverlayConfig;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Archived At
     */
    archived_at: string | null;
};

/**
 * ClipOut
 */
export type ClipOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Origin
     */
    origin: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Detail
     */
    error_detail: string | null;
    /**
     * Source Url
     */
    source_url: string | null;
    /**
     * Original Filename
     */
    original_filename: string | null;
    /**
     * Platform
     */
    platform: string | null;
    /**
     * Source Creator Handle
     */
    source_creator_handle: string | null;
    /**
     * Has Watermark
     */
    has_watermark: boolean | null;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Width
     */
    width: number | null;
    /**
     * Height
     */
    height: number | null;
    /**
     * Fps
     */
    fps: number | null;
    /**
     * Video Codec
     */
    video_codec: string | null;
    /**
     * Color Transfer
     */
    color_transfer: string | null;
    /**
     * Has Audio
     */
    has_audio: boolean | null;
    /**
     * Uploaded At
     */
    uploaded_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CoverOut
 */
export type CoverOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RenderDetail
 */
export type RenderDetailWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Filter
     */
    filter: string | null;
    music: RenderMusic | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Ffmpeg Log
     */
    ffmpeg_log: string | null;
};

/**
 * RenderOut
 */
export type RenderOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Filter
     */
    filter: string | null;
    music: RenderMusic | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * TrackOut
 */
export type TrackOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
};

export type SignupStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/signup-status';
};

export type SignupStatusResponses = {
    /**
     * Successful Response
     */
    200: SignupStatus;
};

export type SignupStatusResponse = SignupStatusResponses[keyof SignupStatusResponses];

export type SignupData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type SignupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * Successful Response
     */
    201: UserOut;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type LoginData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ChangePasswordData = {
    body: PasswordChange;
    path?: never;
    query?: never;
    url: '/api/me/password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type DeleteZernioKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/zernio-key';
};

export type DeleteZernioKeyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteZernioKeyResponse = DeleteZernioKeyResponses[keyof DeleteZernioKeyResponses];

export type PutZernioKeyData = {
    body: ZernioKeyIn;
    path?: never;
    query?: never;
    url: '/api/me/zernio-key';
};

export type PutZernioKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutZernioKeyError = PutZernioKeyErrors[keyof PutZernioKeyErrors];

export type PutZernioKeyResponses = {
    /**
     * Successful Response
     */
    200: KeyCheck;
};

export type PutZernioKeyResponse = PutZernioKeyResponses[keyof PutZernioKeyResponses];

export type CheckZernioKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/zernio-key/check';
};

export type CheckZernioKeyResponses = {
    /**
     * Successful Response
     */
    200: KeyCheck;
};

export type CheckZernioKeyResponse = CheckZernioKeyResponses[keyof CheckZernioKeyResponses];

export type ListBotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/bots';
};

export type ListBotsResponses = {
    /**
     * Response List Bots
     *
     * Successful Response
     */
    200: Array<BotOut>;
};

export type ListBotsResponse = ListBotsResponses[keyof ListBotsResponses];

export type AddBotData = {
    body: BotIn;
    path?: never;
    query?: never;
    url: '/api/me/bots';
};

export type AddBotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddBotError = AddBotErrors[keyof AddBotErrors];

export type AddBotResponses = {
    /**
     * Successful Response
     */
    201: BotPairing;
};

export type AddBotResponse = AddBotResponses[keyof AddBotResponses];

export type PairBotData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/me/bots/{id}/pair';
};

export type PairBotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PairBotError = PairBotErrors[keyof PairBotErrors];

export type PairBotResponses = {
    /**
     * Successful Response
     */
    200: BotPairing;
};

export type PairBotResponse = PairBotResponses[keyof PairBotResponses];

export type DeleteBotData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/me/bots/{id}';
};

export type DeleteBotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBotError = DeleteBotErrors[keyof DeleteBotErrors];

export type DeleteBotResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteBotResponse = DeleteBotResponses[keyof DeleteBotResponses];

export type PatchBotData = {
    body: BotPatch;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/me/bots/{id}';
};

export type PatchBotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchBotError = PatchBotErrors[keyof PatchBotErrors];

export type PatchBotResponses = {
    /**
     * Successful Response
     */
    200: BotOut;
};

export type PatchBotResponse = PatchBotResponses[keyof PatchBotResponses];

export type TestBotData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/me/bots/{id}/test';
};

export type TestBotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestBotError = TestBotErrors[keyof TestBotErrors];

export type TestBotResponses = {
    /**
     * Successful Response
     */
    200: BotTest;
};

export type TestBotResponse = TestBotResponses[keyof TestBotResponses];

export type ListClipsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/clips';
};

export type ListClipsResponses = {
    /**
     * Response List Clips
     *
     * Successful Response
     */
    200: Array<ClipOut>;
};

export type ListClipsResponse = ListClipsResponses[keyof ListClipsResponses];

export type UploadClipData = {
    body: {
        /**
         * .mp4, .mov or .webm
         */
        file: Blob | File;
        source_creator_handle?: string;
    };
    path?: never;
    query?: never;
    url: '/api/clips';
};

export type UploadClipResponses = {
    /**
     * Successful Response
     */
    201: ClipOut;
};

export type UploadClipResponse = UploadClipResponses[keyof UploadClipResponses];

export type CreateClipFromUrlData = {
    body: ClipFromUrl;
    path?: never;
    query?: never;
    url: '/api/clips/from-url';
};

export type CreateClipFromUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClipFromUrlError = CreateClipFromUrlErrors[keyof CreateClipFromUrlErrors];

export type CreateClipFromUrlResponses = {
    /**
     * Successful Response
     */
    201: ClipOut;
};

export type CreateClipFromUrlResponse = CreateClipFromUrlResponses[keyof CreateClipFromUrlResponses];

export type FindLinksData = {
    body: BodyFindLinks;
    path?: never;
    query?: never;
    url: '/api/clips/links';
};

export type FindLinksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FindLinksError = FindLinksErrors[keyof FindLinksErrors];

export type FindLinksResponses = {
    /**
     * Successful Response
     */
    200: LinksOut;
};

export type FindLinksResponse = FindLinksResponses[keyof FindLinksResponses];

export type CreateClipsFromUrlsData = {
    body: ClipsFromUrls;
    path?: never;
    query?: never;
    url: '/api/clips/from-urls';
};

export type CreateClipsFromUrlsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClipsFromUrlsError = CreateClipsFromUrlsErrors[keyof CreateClipsFromUrlsErrors];

export type CreateClipsFromUrlsResponses = {
    /**
     * Successful Response
     */
    201: ClipsFromUrlsOut;
};

export type CreateClipsFromUrlsResponse = CreateClipsFromUrlsResponses[keyof CreateClipsFromUrlsResponses];

export type DeleteClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: {
        /**
         * Renders
         */
        renders?: boolean;
    };
    url: '/api/clips/{clip_id}';
};

export type DeleteClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClipError = DeleteClipErrors[keyof DeleteClipErrors];

export type DeleteClipResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteClipResponse = DeleteClipResponses[keyof DeleteClipResponses];

export type GetClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}';
};

export type GetClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetClipError = GetClipErrors[keyof GetClipErrors];

export type GetClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type GetClipResponse = GetClipResponses[keyof GetClipResponses];

export type UpdateClipData = {
    body: ClipPatch;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}';
};

export type UpdateClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClipError = UpdateClipErrors[keyof UpdateClipErrors];

export type UpdateClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type UpdateClipResponse = UpdateClipResponses[keyof UpdateClipResponses];

export type RetryClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}/retry';
};

export type RetryClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryClipError = RetryClipErrors[keyof RetryClipErrors];

export type RetryClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type RetryClipResponse = RetryClipResponses[keyof RetryClipResponses];

export type ListBrandsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Archived
         */
        archived?: boolean;
    };
    url: '/api/brands';
};

export type ListBrandsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBrandsError = ListBrandsErrors[keyof ListBrandsErrors];

export type ListBrandsResponses = {
    /**
     * Response List Brands
     *
     * Successful Response
     */
    200: Array<BrandOut>;
};

export type ListBrandsResponse = ListBrandsResponses[keyof ListBrandsResponses];

export type CreateBrandData = {
    body: BrandCreate;
    path?: never;
    query?: never;
    url: '/api/brands';
};

export type CreateBrandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBrandError = CreateBrandErrors[keyof CreateBrandErrors];

export type CreateBrandResponses = {
    /**
     * Successful Response
     */
    201: BrandOut;
};

export type CreateBrandResponse = CreateBrandResponses[keyof CreateBrandResponses];

export type UpdateBrandData = {
    body: BrandPatch;
    path: {
        /**
         * Brand Id
         */
        brand_id: number;
    };
    query?: never;
    url: '/api/brands/{brand_id}';
};

export type UpdateBrandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBrandError = UpdateBrandErrors[keyof UpdateBrandErrors];

export type UpdateBrandResponses = {
    /**
     * Successful Response
     */
    200: BrandOut;
};

export type UpdateBrandResponse = UpdateBrandResponses[keyof UpdateBrandResponses];

export type UploadBrandLogoData = {
    body: BodyUploadBrandLogo;
    path: {
        /**
         * Brand Id
         */
        brand_id: number;
    };
    query?: never;
    url: '/api/brands/{brand_id}/logo';
};

export type UploadBrandLogoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadBrandLogoError = UploadBrandLogoErrors[keyof UploadBrandLogoErrors];

export type UploadBrandLogoResponses = {
    /**
     * Successful Response
     */
    200: BrandOut;
};

export type UploadBrandLogoResponse = UploadBrandLogoResponses[keyof UploadBrandLogoResponses];

export type ListRendersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Clip Id
         */
        clip_id?: number | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Unscheduled
         */
        unscheduled?: boolean;
    };
    url: '/api/renders';
};

export type ListRendersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRendersError = ListRendersErrors[keyof ListRendersErrors];

export type ListRendersResponses = {
    /**
     * Response List Renders
     *
     * Successful Response
     */
    200: Array<RenderOut>;
};

export type ListRendersResponse = ListRendersResponses[keyof ListRendersResponses];

export type CreateRenderData = {
    body: RenderCreate;
    path?: never;
    query?: never;
    url: '/api/renders';
};

export type CreateRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRenderError = CreateRenderErrors[keyof CreateRenderErrors];

export type CreateRenderResponses = {
    /**
     * Successful Response
     */
    201: RenderOut;
};

export type CreateRenderResponse = CreateRenderResponses[keyof CreateRenderResponses];

export type ListFiltersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/filters';
};

export type ListFiltersResponses = {
    /**
     * Response List Filters
     *
     * Successful Response
     */
    200: Array<FilterOut>;
};

export type ListFiltersResponse = ListFiltersResponses[keyof ListFiltersResponses];

export type DeleteRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}';
};

export type DeleteRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRenderError = DeleteRenderErrors[keyof DeleteRenderErrors];

export type DeleteRenderResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRenderResponse = DeleteRenderResponses[keyof DeleteRenderResponses];

export type GetRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}';
};

export type GetRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRenderError = GetRenderErrors[keyof GetRenderErrors];

export type GetRenderResponses = {
    /**
     * Successful Response
     */
    200: RenderDetail;
};

export type GetRenderResponse = GetRenderResponses[keyof GetRenderResponses];

export type RetryRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}/retry';
};

export type RetryRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryRenderError = RetryRenderErrors[keyof RetryRenderErrors];

export type RetryRenderResponses = {
    /**
     * Successful Response
     */
    200: RenderOut;
};

export type RetryRenderResponse = RetryRenderResponses[keyof RetryRenderResponses];

export type FreePublishedRendersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Dry Run
         */
        dry_run?: boolean;
    };
    url: '/api/renders/free-published';
};

export type FreePublishedRendersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FreePublishedRendersError = FreePublishedRendersErrors[keyof FreePublishedRendersErrors];

export type FreePublishedRendersResponses = {
    /**
     * Successful Response
     */
    200: FreedSpace;
};

export type FreePublishedRendersResponse = FreePublishedRendersResponses[keyof FreePublishedRendersResponses];

export type DeleteRenderCoverData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}/cover';
};

export type DeleteRenderCoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRenderCoverError = DeleteRenderCoverErrors[keyof DeleteRenderCoverErrors];

export type DeleteRenderCoverResponses = {
    /**
     * Successful Response
     */
    200: RenderOut;
};

export type DeleteRenderCoverResponse = DeleteRenderCoverResponses[keyof DeleteRenderCoverResponses];

export type SetRenderCoverData = {
    body: BodySetRenderCover;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}/cover';
};

export type SetRenderCoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetRenderCoverError = SetRenderCoverErrors[keyof SetRenderCoverErrors];

export type SetRenderCoverResponses = {
    /**
     * Successful Response
     */
    200: RenderOut;
};

export type SetRenderCoverResponse = SetRenderCoverResponses[keyof SetRenderCoverResponses];

export type ListCaptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/captions';
};

export type ListCaptionsResponses = {
    /**
     * Response List Captions
     *
     * Successful Response
     */
    200: Array<CaptionOut>;
};

export type ListCaptionsResponse = ListCaptionsResponses[keyof ListCaptionsResponses];

export type CreateCaptionData = {
    body: CaptionCreate;
    path?: never;
    query?: never;
    url: '/api/captions';
};

export type CreateCaptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCaptionError = CreateCaptionErrors[keyof CreateCaptionErrors];

export type CreateCaptionResponses = {
    /**
     * Successful Response
     */
    201: CaptionOut;
};

export type CreateCaptionResponse = CreateCaptionResponses[keyof CreateCaptionResponses];

export type DeleteCaptionData = {
    body?: never;
    path: {
        /**
         * Caption Id
         */
        caption_id: number;
    };
    query?: never;
    url: '/api/captions/{caption_id}';
};

export type DeleteCaptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCaptionError = DeleteCaptionErrors[keyof DeleteCaptionErrors];

export type DeleteCaptionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCaptionResponse = DeleteCaptionResponses[keyof DeleteCaptionResponses];

export type UpdateCaptionData = {
    body: CaptionPatch;
    path: {
        /**
         * Caption Id
         */
        caption_id: number;
    };
    query?: never;
    url: '/api/captions/{caption_id}';
};

export type UpdateCaptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCaptionError = UpdateCaptionErrors[keyof UpdateCaptionErrors];

export type UpdateCaptionResponses = {
    /**
     * Successful Response
     */
    200: CaptionOut;
};

export type UpdateCaptionResponse = UpdateCaptionResponses[keyof UpdateCaptionResponses];

export type ListCoversData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/covers';
};

export type ListCoversResponses = {
    /**
     * Response List Covers
     *
     * Successful Response
     */
    200: Array<CoverOut>;
};

export type ListCoversResponse = ListCoversResponses[keyof ListCoversResponses];

export type UploadCoverData = {
    body: BodyUploadCover;
    path?: never;
    query?: never;
    url: '/api/covers';
};

export type UploadCoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadCoverError = UploadCoverErrors[keyof UploadCoverErrors];

export type UploadCoverResponses = {
    /**
     * Successful Response
     */
    201: CoverOut;
};

export type UploadCoverResponse = UploadCoverResponses[keyof UploadCoverResponses];

export type DeleteCoverData = {
    body?: never;
    path: {
        /**
         * Cover Id
         */
        cover_id: number;
    };
    query?: never;
    url: '/api/covers/{cover_id}';
};

export type DeleteCoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCoverError = DeleteCoverErrors[keyof DeleteCoverErrors];

export type DeleteCoverResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCoverResponse = DeleteCoverResponses[keyof DeleteCoverResponses];

export type UpdateCoverData = {
    body: CoverPatch;
    path: {
        /**
         * Cover Id
         */
        cover_id: number;
    };
    query?: never;
    url: '/api/covers/{cover_id}';
};

export type UpdateCoverErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCoverError = UpdateCoverErrors[keyof UpdateCoverErrors];

export type UpdateCoverResponses = {
    /**
     * Successful Response
     */
    200: CoverOut;
};

export type UpdateCoverResponse = UpdateCoverResponses[keyof UpdateCoverResponses];

export type ListTracksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tracks';
};

export type ListTracksResponses = {
    /**
     * Response List Tracks
     *
     * Successful Response
     */
    200: Array<TrackOut>;
};

export type ListTracksResponse = ListTracksResponses[keyof ListTracksResponses];

export type UploadTrackData = {
    body: BodyUploadTrack;
    path?: never;
    query?: never;
    url: '/api/tracks';
};

export type UploadTrackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadTrackError = UploadTrackErrors[keyof UploadTrackErrors];

export type UploadTrackResponses = {
    /**
     * Successful Response
     */
    201: TrackOut;
};

export type UploadTrackResponse = UploadTrackResponses[keyof UploadTrackResponses];

export type DeleteTrackData = {
    body?: never;
    path: {
        /**
         * Track Id
         */
        track_id: number;
    };
    query?: never;
    url: '/api/tracks/{track_id}';
};

export type DeleteTrackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTrackError = DeleteTrackErrors[keyof DeleteTrackErrors];

export type DeleteTrackResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTrackResponse = DeleteTrackResponses[keyof DeleteTrackResponses];

export type UpdateTrackData = {
    body: TrackPatch;
    path: {
        /**
         * Track Id
         */
        track_id: number;
    };
    query?: never;
    url: '/api/tracks/{track_id}';
};

export type UpdateTrackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTrackError = UpdateTrackErrors[keyof UpdateTrackErrors];

export type UpdateTrackResponses = {
    /**
     * Successful Response
     */
    200: TrackOut;
};

export type UpdateTrackResponse = UpdateTrackResponses[keyof UpdateTrackResponses];

export type ListAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts';
};

export type ListAccountsResponses = {
    /**
     * Response List Accounts
     *
     * Successful Response
     */
    200: Array<AccountOut>;
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type SyncAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/sync';
};

export type SyncAccountsResponses = {
    /**
     * Response Sync Accounts
     *
     * Successful Response
     */
    200: Array<AccountOut>;
};

export type SyncAccountsResponse = SyncAccountsResponses[keyof SyncAccountsResponses];

export type UpdateAccountData = {
    body: AccountPatch;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/{account_id}';
};

export type UpdateAccountErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
    /**
     * Successful Response
     */
    200: AccountOut;
};

export type UpdateAccountResponse = UpdateAccountResponses[keyof UpdateAccountResponses];

export type NextSlotData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/accounts/{account_id}/next-slot';
};

export type NextSlotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NextSlotError = NextSlotErrors[keyof NextSlotErrors];

export type NextSlotResponses = {
    /**
     * Successful Response
     */
    200: NextSlot;
};

export type NextSlotResponse = NextSlotResponses[keyof NextSlotResponses];

export type SearchMusicData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Kind
         */
        kind?: 'music' | 'original_sound';
    };
    url: '/api/accounts/{account_id}/music';
};

export type SearchMusicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchMusicError = SearchMusicErrors[keyof SearchMusicErrors];

export type SearchMusicResponses = {
    /**
     * Response Search Music
     *
     * Successful Response
     */
    200: Array<MusicOut>;
};

export type SearchMusicResponse = SearchMusicResponses[keyof SearchMusicResponses];

export type ListPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * From
         */
        from?: string | null;
        /**
         * To
         */
        to?: string | null;
        /**
         * Account Id
         */
        account_id?: number | null;
        /**
         * Brand Id
         */
        brand_id?: number | null;
        /**
         * Status
         */
        status?: Array<'DRAFT' | 'SCHEDULED' | 'PUBLISHING' | 'PUBLISHED' | 'FAILED' | 'DEAD_LETTER' | 'CANCELLED'> | null;
    };
    url: '/api/posts';
};

export type ListPostsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPostsError = ListPostsErrors[keyof ListPostsErrors];

export type ListPostsResponses = {
    /**
     * Response List Posts
     *
     * Successful Response
     */
    200: Array<PostOut>;
};

export type ListPostsResponse = ListPostsResponses[keyof ListPostsResponses];

export type CreatePostData = {
    body: PostCreate;
    path?: never;
    query?: never;
    url: '/api/posts';
};

export type CreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
    /**
     * Successful Response
     */
    201: PostOut;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type GetPostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}';
};

export type GetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type UpdatePostData = {
    body: PostPatch;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}';
};

export type UpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePostError = UpdatePostErrors[keyof UpdatePostErrors];

export type UpdatePostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type UpdatePostResponse = UpdatePostResponses[keyof UpdatePostResponses];

export type AutoScheduleData = {
    body: AutoScheduleIn;
    path?: never;
    query?: never;
    url: '/api/posts/auto-schedule';
};

export type AutoScheduleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AutoScheduleError = AutoScheduleErrors[keyof AutoScheduleErrors];

export type AutoScheduleResponses = {
    /**
     * Successful Response
     */
    200: AutoScheduleOut;
};

export type AutoScheduleResponse = AutoScheduleResponses[keyof AutoScheduleResponses];

export type ApprovePostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}/approve';
};

export type ApprovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApprovePostError = ApprovePostErrors[keyof ApprovePostErrors];

export type ApprovePostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type ApprovePostResponse = ApprovePostResponses[keyof ApprovePostResponses];

export type CancelPostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}/cancel';
};

export type CancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelPostError = CancelPostErrors[keyof CancelPostErrors];

export type CancelPostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type CancelPostResponse = CancelPostResponses[keyof CancelPostResponses];

export type RemedyPostData = {
    body: RemedyIn;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/api/posts/{post_id}/remedy';
};

export type RemedyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemedyPostError = RemedyPostErrors[keyof RemedyPostErrors];

export type RemedyPostResponses = {
    /**
     * Successful Response
     */
    200: PostOut;
};

export type RemedyPostResponse = RemedyPostResponses[keyof RemedyPostResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type StatusResponses = {
    /**
     * Successful Response
     */
    200: SystemStatus;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];
