// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_upload_brand_logo
 */
export type BodyUploadBrandLogo = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BrandCreate
 */
export type BrandCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template?: string | null;
    /**
     * Link
     */
    link?: string | null;
    /**
     * Auto Approve
     */
    auto_approve?: boolean;
    default_overlay_config?: OverlayConfig | null;
};

/**
 * BrandOut
 */
export type BrandOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template: string | null;
    /**
     * Link
     */
    link: string | null;
    /**
     * Auto Approve
     */
    auto_approve: boolean;
    default_overlay_config: OverlayConfig;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Archived At
     */
    archived_at: string | null;
    /**
     * Logo Url
     */
    readonly logo_url: string | null;
};

/**
 * BrandPatch
 */
export type BrandPatch = {
    /**
     * Name
     */
    name?: string;
    /**
     * Caption Template
     */
    caption_template?: string | null;
    /**
     * Link
     */
    link?: string | null;
    /**
     * Auto Approve
     */
    auto_approve?: boolean;
    default_overlay_config?: OverlayConfig;
    /**
     * Archived
     */
    archived?: boolean;
};

/**
 * ClipFromUrl
 */
export type ClipFromUrl = {
    /**
     * Url
     */
    url: string;
    /**
     * Rights Status
     */
    rights_status: 'permission_granted' | 'none' | 'own_content';
    /**
     * Source Creator Handle
     */
    source_creator_handle?: string | null;
};

/**
 * ClipOut
 */
export type ClipOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Origin
     */
    origin: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Detail
     */
    error_detail: string | null;
    /**
     * Source Url
     */
    source_url: string | null;
    /**
     * Original Filename
     */
    original_filename: string | null;
    /**
     * Platform
     */
    platform: string | null;
    /**
     * Source Creator Handle
     */
    source_creator_handle: string | null;
    /**
     * Rights Status
     */
    rights_status: 'permission_granted' | 'none' | 'own_content';
    /**
     * Has Watermark
     */
    has_watermark: boolean | null;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Width
     */
    width: number | null;
    /**
     * Height
     */
    height: number | null;
    /**
     * Fps
     */
    fps: number | null;
    /**
     * Video Codec
     */
    video_codec: string | null;
    /**
     * Color Transfer
     */
    color_transfer: string | null;
    /**
     * Has Audio
     */
    has_audio: boolean | null;
    /**
     * Uploaded At
     */
    uploaded_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Raw Url
     */
    readonly raw_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * ClipPatch
 */
export type ClipPatch = {
    /**
     * Rights Status
     */
    rights_status?: 'permission_granted' | 'none' | 'own_content';
    /**
     * Source Creator Handle
     */
    source_creator_handle?: string | null;
    /**
     * Has Watermark
     */
    has_watermark?: boolean | null;
};

/**
 * CropConfig
 *
 * Crop rectangle as fractions of the source frame (after autorotate).
 */
export type CropConfig = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * W
     */
    w: number;
    /**
     * H
     */
    h: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status: string;
};

/**
 * OverlayConfig
 *
 * Logo box as fractions of the 1080x1920 output: top-left x, y and width (height follows the logo,
 * so only y < 1 is checked here).
 */
export type OverlayConfig = {
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * W
     */
    w: number;
    /**
     * Opacity
     */
    opacity?: number;
};

/**
 * RenderCreate
 */
export type RenderCreate = {
    /**
     * Clip Id
     */
    clip_id: number;
    /**
     * Brand Id
     */
    brand_id?: number | null;
    overlay_config?: OverlayConfig | null;
    crop_config?: CropConfig | null;
    /**
     * Caption
     */
    caption?: string | null;
};

/**
 * RenderDetail
 */
export type RenderDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Ffmpeg Log
     */
    ffmpeg_log: string | null;
    /**
     * Output Url
     */
    readonly output_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * RenderOut
 */
export type RenderOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Output Url
     */
    readonly output_url: string | null;
    /**
     * Thumbnail Url
     */
    readonly thumbnail_url: string | null;
};

/**
 * SystemStatus
 */
export type SystemStatus = {
    /**
     * Db
     */
    db: boolean;
    /**
     * Worker Alive
     */
    worker_alive: boolean;
    /**
     * Worker Last Heartbeat
     */
    worker_last_heartbeat: string | null;
    /**
     * Jobs
     */
    jobs: {
        [key: string]: number;
    };
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * BrandOut
 */
export type BrandOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Caption Template
     */
    caption_template: string | null;
    /**
     * Link
     */
    link: string | null;
    /**
     * Auto Approve
     */
    auto_approve: boolean;
    default_overlay_config: OverlayConfig;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Archived At
     */
    archived_at: string | null;
};

/**
 * ClipOut
 */
export type ClipOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Origin
     */
    origin: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Detail
     */
    error_detail: string | null;
    /**
     * Source Url
     */
    source_url: string | null;
    /**
     * Original Filename
     */
    original_filename: string | null;
    /**
     * Platform
     */
    platform: string | null;
    /**
     * Source Creator Handle
     */
    source_creator_handle: string | null;
    /**
     * Rights Status
     */
    rights_status: 'permission_granted' | 'none' | 'own_content';
    /**
     * Has Watermark
     */
    has_watermark: boolean | null;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Width
     */
    width: number | null;
    /**
     * Height
     */
    height: number | null;
    /**
     * Fps
     */
    fps: number | null;
    /**
     * Video Codec
     */
    video_codec: string | null;
    /**
     * Color Transfer
     */
    color_transfer: string | null;
    /**
     * Has Audio
     */
    has_audio: boolean | null;
    /**
     * Uploaded At
     */
    uploaded_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RenderDetail
 */
export type RenderDetailWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Ffmpeg Log
     */
    ffmpeg_log: string | null;
};

/**
 * RenderOut
 */
export type RenderOutWritable = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Clip Id
     */
    source_clip_id: number;
    /**
     * Brand Id
     */
    brand_id: number | null;
    overlay_config: OverlayConfig | null;
    crop_config: CropConfig | null;
    /**
     * Caption
     */
    caption: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Size Bytes
     */
    size_bytes: number | null;
    /**
     * Duration S
     */
    duration_s: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

export type ListClipsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/clips';
};

export type ListClipsResponses = {
    /**
     * Response List Clips
     *
     * Successful Response
     */
    200: Array<ClipOut>;
};

export type ListClipsResponse = ListClipsResponses[keyof ListClipsResponses];

export type UploadClipData = {
    body: {
        /**
         * .mp4, .mov or .webm
         */
        file: Blob | File;
        rights_status: 'permission_granted' | 'none' | 'own_content';
        source_creator_handle?: string;
    };
    path?: never;
    query?: never;
    url: '/api/clips';
};

export type UploadClipResponses = {
    /**
     * Successful Response
     */
    201: ClipOut;
};

export type UploadClipResponse = UploadClipResponses[keyof UploadClipResponses];

export type CreateClipFromUrlData = {
    body: ClipFromUrl;
    path?: never;
    query?: never;
    url: '/api/clips/from-url';
};

export type CreateClipFromUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClipFromUrlError = CreateClipFromUrlErrors[keyof CreateClipFromUrlErrors];

export type CreateClipFromUrlResponses = {
    /**
     * Successful Response
     */
    201: ClipOut;
};

export type CreateClipFromUrlResponse = CreateClipFromUrlResponses[keyof CreateClipFromUrlResponses];

export type DeleteClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}';
};

export type DeleteClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClipError = DeleteClipErrors[keyof DeleteClipErrors];

export type DeleteClipResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteClipResponse = DeleteClipResponses[keyof DeleteClipResponses];

export type GetClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}';
};

export type GetClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetClipError = GetClipErrors[keyof GetClipErrors];

export type GetClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type GetClipResponse = GetClipResponses[keyof GetClipResponses];

export type UpdateClipData = {
    body: ClipPatch;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}';
};

export type UpdateClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClipError = UpdateClipErrors[keyof UpdateClipErrors];

export type UpdateClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type UpdateClipResponse = UpdateClipResponses[keyof UpdateClipResponses];

export type RetryClipData = {
    body?: never;
    path: {
        /**
         * Clip Id
         */
        clip_id: number;
    };
    query?: never;
    url: '/api/clips/{clip_id}/retry';
};

export type RetryClipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryClipError = RetryClipErrors[keyof RetryClipErrors];

export type RetryClipResponses = {
    /**
     * Successful Response
     */
    200: ClipOut;
};

export type RetryClipResponse = RetryClipResponses[keyof RetryClipResponses];

export type ListBrandsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Archived
         */
        archived?: boolean;
    };
    url: '/api/brands';
};

export type ListBrandsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListBrandsError = ListBrandsErrors[keyof ListBrandsErrors];

export type ListBrandsResponses = {
    /**
     * Response List Brands
     *
     * Successful Response
     */
    200: Array<BrandOut>;
};

export type ListBrandsResponse = ListBrandsResponses[keyof ListBrandsResponses];

export type CreateBrandData = {
    body: BrandCreate;
    path?: never;
    query?: never;
    url: '/api/brands';
};

export type CreateBrandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBrandError = CreateBrandErrors[keyof CreateBrandErrors];

export type CreateBrandResponses = {
    /**
     * Successful Response
     */
    201: BrandOut;
};

export type CreateBrandResponse = CreateBrandResponses[keyof CreateBrandResponses];

export type UpdateBrandData = {
    body: BrandPatch;
    path: {
        /**
         * Brand Id
         */
        brand_id: number;
    };
    query?: never;
    url: '/api/brands/{brand_id}';
};

export type UpdateBrandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBrandError = UpdateBrandErrors[keyof UpdateBrandErrors];

export type UpdateBrandResponses = {
    /**
     * Successful Response
     */
    200: BrandOut;
};

export type UpdateBrandResponse = UpdateBrandResponses[keyof UpdateBrandResponses];

export type UploadBrandLogoData = {
    body: BodyUploadBrandLogo;
    path: {
        /**
         * Brand Id
         */
        brand_id: number;
    };
    query?: never;
    url: '/api/brands/{brand_id}/logo';
};

export type UploadBrandLogoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadBrandLogoError = UploadBrandLogoErrors[keyof UploadBrandLogoErrors];

export type UploadBrandLogoResponses = {
    /**
     * Successful Response
     */
    200: BrandOut;
};

export type UploadBrandLogoResponse = UploadBrandLogoResponses[keyof UploadBrandLogoResponses];

export type ListRendersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Clip Id
         */
        clip_id?: number | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Unscheduled
         */
        unscheduled?: boolean;
    };
    url: '/api/renders';
};

export type ListRendersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRendersError = ListRendersErrors[keyof ListRendersErrors];

export type ListRendersResponses = {
    /**
     * Response List Renders
     *
     * Successful Response
     */
    200: Array<RenderOut>;
};

export type ListRendersResponse = ListRendersResponses[keyof ListRendersResponses];

export type CreateRenderData = {
    body: RenderCreate;
    path?: never;
    query?: never;
    url: '/api/renders';
};

export type CreateRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRenderError = CreateRenderErrors[keyof CreateRenderErrors];

export type CreateRenderResponses = {
    /**
     * Successful Response
     */
    201: RenderOut;
};

export type CreateRenderResponse = CreateRenderResponses[keyof CreateRenderResponses];

export type DeleteRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}';
};

export type DeleteRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRenderError = DeleteRenderErrors[keyof DeleteRenderErrors];

export type DeleteRenderResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRenderResponse = DeleteRenderResponses[keyof DeleteRenderResponses];

export type GetRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}';
};

export type GetRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRenderError = GetRenderErrors[keyof GetRenderErrors];

export type GetRenderResponses = {
    /**
     * Successful Response
     */
    200: RenderDetail;
};

export type GetRenderResponse = GetRenderResponses[keyof GetRenderResponses];

export type RetryRenderData = {
    body?: never;
    path: {
        /**
         * Render Id
         */
        render_id: number;
    };
    query?: never;
    url: '/api/renders/{render_id}/retry';
};

export type RetryRenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryRenderError = RetryRenderErrors[keyof RetryRenderErrors];

export type RetryRenderResponses = {
    /**
     * Successful Response
     */
    200: RenderOut;
};

export type RetryRenderResponse = RetryRenderResponses[keyof RetryRenderResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type StatusResponses = {
    /**
     * Successful Response
     */
    200: SystemStatus;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];
