// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createBrand, createClipFromUrl, createRender, deleteClip, deleteRender, getClip, getRender, health, listBrands, listClips, listRenders, type Options, retryClip, retryRender, status, updateBrand, updateClip, uploadBrandLogo, uploadClip } from '../sdk.gen';
import type { CreateBrandData, CreateBrandError, CreateBrandResponse, CreateClipFromUrlData, CreateClipFromUrlError, CreateClipFromUrlResponse, CreateRenderData, CreateRenderError, CreateRenderResponse, DeleteClipData, DeleteClipError, DeleteClipResponse, DeleteRenderData, DeleteRenderError, DeleteRenderResponse, GetClipData, GetClipError, GetClipResponse, GetRenderData, GetRenderError, GetRenderResponse, HealthData, HealthResponse, ListBrandsData, ListBrandsError, ListBrandsResponse, ListClipsData, ListClipsResponse, ListRendersData, ListRendersError, ListRendersResponse, RetryClipData, RetryClipError, RetryClipResponse, RetryRenderData, RetryRenderError, RetryRenderResponse, StatusData, StatusResponse, UpdateBrandData, UpdateBrandError, UpdateBrandResponse, UpdateClipData, UpdateClipError, UpdateClipResponse, UploadBrandLogoData, UploadBrandLogoError, UploadBrandLogoResponse, UploadClipData, UploadClipResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listClipsQueryKey = (options?: Options<ListClipsData>) => createQueryKey('listClips', options);

/**
 * List Clips
 */
export const listClipsOptions = (options?: Options<ListClipsData>) => queryOptions<ListClipsResponse, DefaultError, ListClipsResponse, ReturnType<typeof listClipsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listClips({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listClipsQueryKey(options)
});

/**
 * Upload Clip
 *
 * Multipart upload, streamed to raw/. The clip is UPLOADING while the bytes arrive, then PROBING.
 */
export const uploadClipMutation = (options?: Partial<Options<UploadClipData>>): UseMutationOptions<UploadClipResponse, DefaultError, Options<UploadClipData>> => {
    const mutationOptions: UseMutationOptions<UploadClipResponse, DefaultError, Options<UploadClipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadClip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Clip From Url
 */
export const createClipFromUrlMutation = (options?: Partial<Options<CreateClipFromUrlData>>): UseMutationOptions<CreateClipFromUrlResponse, CreateClipFromUrlError, Options<CreateClipFromUrlData>> => {
    const mutationOptions: UseMutationOptions<CreateClipFromUrlResponse, CreateClipFromUrlError, Options<CreateClipFromUrlData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createClipFromUrl({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Clip
 *
 * Only READY/FAILED clips with no renders (delete the renders first). Files go too.
 */
export const deleteClipMutation = (options?: Partial<Options<DeleteClipData>>): UseMutationOptions<DeleteClipResponse, DeleteClipError, Options<DeleteClipData>> => {
    const mutationOptions: UseMutationOptions<DeleteClipResponse, DeleteClipError, Options<DeleteClipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteClip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getClipQueryKey = (options: Options<GetClipData>) => createQueryKey('getClip', options);

/**
 * Get Clip
 */
export const getClipOptions = (options: Options<GetClipData>) => queryOptions<GetClipResponse, GetClipError, GetClipResponse, ReturnType<typeof getClipQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getClip({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getClipQueryKey(options)
});

/**
 * Update Clip
 */
export const updateClipMutation = (options?: Partial<Options<UpdateClipData>>): UseMutationOptions<UpdateClipResponse, UpdateClipError, Options<UpdateClipData>> => {
    const mutationOptions: UseMutationOptions<UpdateClipResponse, UpdateClipError, Options<UpdateClipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateClip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Retry Clip
 *
 * FAILED -> PROBING again if the bytes are here, else DOWNLOADING again (url clips).
 */
export const retryClipMutation = (options?: Partial<Options<RetryClipData>>): UseMutationOptions<RetryClipResponse, RetryClipError, Options<RetryClipData>> => {
    const mutationOptions: UseMutationOptions<RetryClipResponse, RetryClipError, Options<RetryClipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await retryClip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBrandsQueryKey = (options?: Options<ListBrandsData>) => createQueryKey('listBrands', options);

/**
 * List Brands
 */
export const listBrandsOptions = (options?: Options<ListBrandsData>) => queryOptions<ListBrandsResponse, ListBrandsError, ListBrandsResponse, ReturnType<typeof listBrandsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBrands({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBrandsQueryKey(options)
});

/**
 * Create Brand
 */
export const createBrandMutation = (options?: Partial<Options<CreateBrandData>>): UseMutationOptions<CreateBrandResponse, CreateBrandError, Options<CreateBrandData>> => {
    const mutationOptions: UseMutationOptions<CreateBrandResponse, CreateBrandError, Options<CreateBrandData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBrand({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Brand
 */
export const updateBrandMutation = (options?: Partial<Options<UpdateBrandData>>): UseMutationOptions<UpdateBrandResponse, UpdateBrandError, Options<UpdateBrandData>> => {
    const mutationOptions: UseMutationOptions<UpdateBrandResponse, UpdateBrandError, Options<UpdateBrandData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBrand({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload Brand Logo
 *
 * A PNG with transparency. Stored under a new name each time, so browsers never show a stale logo.
 */
export const uploadBrandLogoMutation = (options?: Partial<Options<UploadBrandLogoData>>): UseMutationOptions<UploadBrandLogoResponse, UploadBrandLogoError, Options<UploadBrandLogoData>> => {
    const mutationOptions: UseMutationOptions<UploadBrandLogoResponse, UploadBrandLogoError, Options<UploadBrandLogoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadBrandLogo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRendersQueryKey = (options?: Options<ListRendersData>) => createQueryKey('listRenders', options);

/**
 * List Renders
 *
 * unscheduled: renders with no post other than CANCELLED ones.
 */
export const listRendersOptions = (options?: Options<ListRendersData>) => queryOptions<ListRendersResponse, ListRendersError, ListRendersResponse, ReturnType<typeof listRendersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRenders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRendersQueryKey(options)
});

/**
 * Create Render
 */
export const createRenderMutation = (options?: Partial<Options<CreateRenderData>>): UseMutationOptions<CreateRenderResponse, CreateRenderError, Options<CreateRenderData>> => {
    const mutationOptions: UseMutationOptions<CreateRenderResponse, CreateRenderError, Options<CreateRenderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRender({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Render
 *
 * Not while RENDERING, and not once any post refers to it. Files go too.
 */
export const deleteRenderMutation = (options?: Partial<Options<DeleteRenderData>>): UseMutationOptions<DeleteRenderResponse, DeleteRenderError, Options<DeleteRenderData>> => {
    const mutationOptions: UseMutationOptions<DeleteRenderResponse, DeleteRenderError, Options<DeleteRenderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRender({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRenderQueryKey = (options: Options<GetRenderData>) => createQueryKey('getRender', options);

/**
 * Get Render
 */
export const getRenderOptions = (options: Options<GetRenderData>) => queryOptions<GetRenderResponse, GetRenderError, GetRenderResponse, ReturnType<typeof getRenderQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRender({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRenderQueryKey(options)
});

/**
 * Retry Render
 */
export const retryRenderMutation = (options?: Partial<Options<RetryRenderData>>): UseMutationOptions<RetryRenderResponse, RetryRenderError, Options<RetryRenderData>> => {
    const mutationOptions: UseMutationOptions<RetryRenderResponse, RetryRenderError, Options<RetryRenderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await retryRender({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Health
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse, DefaultError, HealthResponse, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});

export const statusQueryKey = (options?: Options<StatusData>) => createQueryKey('status', options);

/**
 * Status
 */
export const statusOptions = (options?: Options<StatusData>) => queryOptions<StatusResponse, DefaultError, StatusResponse, ReturnType<typeof statusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await status({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: statusQueryKey(options)
});
