// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { approvePost, autoSchedule, cancelPost, createBrand, createClipFromUrl, createClipsFromUrls, createPost, createRender, deleteClip, deleteRender, deleteRenderCover, findLinks, getClip, getPost, getRender, health, listAccounts, listBrands, listClips, listPosts, listRenders, nextSlot, type Options, remedyPost, retryClip, retryRender, setRenderCover, status, syncAccounts, updateAccount, updateBrand, updateClip, updatePost, uploadBrandLogo, uploadClip } from '../sdk.gen';
import type { ApprovePostData, ApprovePostError, ApprovePostResponse, AutoScheduleData, AutoScheduleError, AutoScheduleResponse, CancelPostData, CancelPostError, CancelPostResponse, CreateBrandData, CreateBrandError, CreateBrandResponse, CreateClipFromUrlData, CreateClipFromUrlError, CreateClipFromUrlResponse, CreateClipsFromUrlsData, CreateClipsFromUrlsError, CreateClipsFromUrlsResponse, CreatePostData, CreatePostError, CreatePostResponse, CreateRenderData, CreateRenderError, CreateRenderResponse, DeleteClipData, DeleteClipError, DeleteClipResponse, DeleteRenderCoverData, DeleteRenderCoverError, DeleteRenderCoverResponse, DeleteRenderData, DeleteRenderError, DeleteRenderResponse, FindLinksData, FindLinksError, FindLinksResponse, GetClipData, GetClipError, GetClipResponse, GetPostData, GetPostError, GetPostResponse, GetRenderData, GetRenderError, GetRenderResponse, HealthData, HealthResponse, ListAccountsData, ListAccountsResponse, ListBrandsData, ListBrandsError, ListBrandsResponse, ListClipsData, ListClipsResponse, ListPostsData, ListPostsError, ListPostsResponse, ListRendersData, ListRendersError, ListRendersResponse, NextSlotData, NextSlotError, NextSlotResponse, RemedyPostData, RemedyPostError, RemedyPostResponse, RetryClipData, RetryClipError, RetryClipResponse, RetryRenderData, RetryRenderError, RetryRenderResponse, SetRenderCoverData, SetRenderCoverError, SetRenderCoverResponse, StatusData, StatusResponse, SyncAccountsData, SyncAccountsResponse, UpdateAccountData, UpdateAccountError, UpdateAccountResponse, UpdateBrandData, UpdateBrandError, UpdateBrandResponse, UpdateClipData, UpdateClipError, UpdateClipResponse, UpdatePostData, UpdatePostError, UpdatePostResponse, UploadBrandLogoData, UploadBrandLogoError, UploadBrandLogoResponse, UploadClipData, UploadClipResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listClipsQueryKey = (options?: Options<ListClipsData>) => createQueryKey('listClips', options);

/**
 * List Clips
 */
export const listClipsOptions = (options?: Options<ListClipsData>) => queryOptions<ListClipsResponse, DefaultError, ListClipsResponse, ReturnType<typeof listClipsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listClips({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listClipsQueryKey(options)
});

/**
 * Upload Clip
 *
 * Multipart upload, streamed to raw/. The clip is UPLOADING while the bytes arrive, then PROBING.
 */
export const uploadClipMutation = (options?: Partial<Options<UploadClipData>>): UseMutationOptions<UploadClipResponse, DefaultError, Options<UploadClipData>> => {
    const mutationOptions: UseMutationOptions<UploadClipResponse, DefaultError, Options<UploadClipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadClip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Clip From Url
 */
export const createClipFromUrlMutation = (options?: Partial<Options<CreateClipFromUrlData>>): UseMutationOptions<CreateClipFromUrlResponse, CreateClipFromUrlError, Options<CreateClipFromUrlData>> => {
    const mutationOptions: UseMutationOptions<CreateClipFromUrlResponse, CreateClipFromUrlError, Options<CreateClipFromUrlData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createClipFromUrl({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Find Links
 *
 * The video links in a document (docx, xlsx, pptx, odt) or a text file. Nothing is imported.
 */
export const findLinksMutation = (options?: Partial<Options<FindLinksData>>): UseMutationOptions<FindLinksResponse, FindLinksError, Options<FindLinksData>> => {
    const mutationOptions: UseMutationOptions<FindLinksResponse, FindLinksError, Options<FindLinksData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await findLinks({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Clips From Urls
 *
 * One DOWNLOADING clip per video that isn't in the library yet.
 */
export const createClipsFromUrlsMutation = (options?: Partial<Options<CreateClipsFromUrlsData>>): UseMutationOptions<CreateClipsFromUrlsResponse, CreateClipsFromUrlsError, Options<CreateClipsFromUrlsData>> => {
    const mutationOptions: UseMutationOptions<CreateClipsFromUrlsResponse, CreateClipsFromUrlsError, Options<CreateClipsFromUrlsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createClipsFromUrls({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Clip
 *
 * Only READY/FAILED clips with no renders (delete the renders first). Files go too.
 */
export const deleteClipMutation = (options?: Partial<Options<DeleteClipData>>): UseMutationOptions<DeleteClipResponse, DeleteClipError, Options<DeleteClipData>> => {
    const mutationOptions: UseMutationOptions<DeleteClipResponse, DeleteClipError, Options<DeleteClipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteClip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getClipQueryKey = (options: Options<GetClipData>) => createQueryKey('getClip', options);

/**
 * Get Clip
 */
export const getClipOptions = (options: Options<GetClipData>) => queryOptions<GetClipResponse, GetClipError, GetClipResponse, ReturnType<typeof getClipQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getClip({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getClipQueryKey(options)
});

/**
 * Update Clip
 */
export const updateClipMutation = (options?: Partial<Options<UpdateClipData>>): UseMutationOptions<UpdateClipResponse, UpdateClipError, Options<UpdateClipData>> => {
    const mutationOptions: UseMutationOptions<UpdateClipResponse, UpdateClipError, Options<UpdateClipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateClip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Retry Clip
 *
 * FAILED -> PROBING again if the bytes are here, else DOWNLOADING again (url clips).
 */
export const retryClipMutation = (options?: Partial<Options<RetryClipData>>): UseMutationOptions<RetryClipResponse, RetryClipError, Options<RetryClipData>> => {
    const mutationOptions: UseMutationOptions<RetryClipResponse, RetryClipError, Options<RetryClipData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await retryClip({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listBrandsQueryKey = (options?: Options<ListBrandsData>) => createQueryKey('listBrands', options);

/**
 * List Brands
 */
export const listBrandsOptions = (options?: Options<ListBrandsData>) => queryOptions<ListBrandsResponse, ListBrandsError, ListBrandsResponse, ReturnType<typeof listBrandsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBrands({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBrandsQueryKey(options)
});

/**
 * Create Brand
 */
export const createBrandMutation = (options?: Partial<Options<CreateBrandData>>): UseMutationOptions<CreateBrandResponse, CreateBrandError, Options<CreateBrandData>> => {
    const mutationOptions: UseMutationOptions<CreateBrandResponse, CreateBrandError, Options<CreateBrandData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBrand({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Brand
 */
export const updateBrandMutation = (options?: Partial<Options<UpdateBrandData>>): UseMutationOptions<UpdateBrandResponse, UpdateBrandError, Options<UpdateBrandData>> => {
    const mutationOptions: UseMutationOptions<UpdateBrandResponse, UpdateBrandError, Options<UpdateBrandData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBrand({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Upload Brand Logo
 *
 * A PNG with transparency. Stored under a new name each time, so browsers never show a stale logo.
 */
export const uploadBrandLogoMutation = (options?: Partial<Options<UploadBrandLogoData>>): UseMutationOptions<UploadBrandLogoResponse, UploadBrandLogoError, Options<UploadBrandLogoData>> => {
    const mutationOptions: UseMutationOptions<UploadBrandLogoResponse, UploadBrandLogoError, Options<UploadBrandLogoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadBrandLogo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRendersQueryKey = (options?: Options<ListRendersData>) => createQueryKey('listRenders', options);

/**
 * List Renders
 *
 * unscheduled: renders with no post other than CANCELLED ones, and not superseded by a re-render.
 */
export const listRendersOptions = (options?: Options<ListRendersData>) => queryOptions<ListRendersResponse, ListRendersError, ListRendersResponse, ReturnType<typeof listRendersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRenders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRendersQueryKey(options)
});

/**
 * Create Render
 */
export const createRenderMutation = (options?: Partial<Options<CreateRenderData>>): UseMutationOptions<CreateRenderResponse, CreateRenderError, Options<CreateRenderData>> => {
    const mutationOptions: UseMutationOptions<CreateRenderResponse, CreateRenderError, Options<CreateRenderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRender({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Render
 *
 * Not while RENDERING, and not while a live (non-CANCELLED) post refers to it. Its CANCELLED posts
 * and files go too. FOR UPDATE: a cover change in flight lands first, so its file is the one deleted.
 */
export const deleteRenderMutation = (options?: Partial<Options<DeleteRenderData>>): UseMutationOptions<DeleteRenderResponse, DeleteRenderError, Options<DeleteRenderData>> => {
    const mutationOptions: UseMutationOptions<DeleteRenderResponse, DeleteRenderError, Options<DeleteRenderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRender({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRenderQueryKey = (options: Options<GetRenderData>) => createQueryKey('getRender', options);

/**
 * Get Render
 */
export const getRenderOptions = (options: Options<GetRenderData>) => queryOptions<GetRenderResponse, GetRenderError, GetRenderResponse, ReturnType<typeof getRenderQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRender({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRenderQueryKey(options)
});

/**
 * Retry Render
 */
export const retryRenderMutation = (options?: Partial<Options<RetryRenderData>>): UseMutationOptions<RetryRenderResponse, RetryRenderError, Options<RetryRenderData>> => {
    const mutationOptions: UseMutationOptions<RetryRenderResponse, RetryRenderError, Options<RetryRenderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await retryRender({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Render Cover
 *
 * Back to Instagram's own pick. 409 once the render has posts.
 */
export const deleteRenderCoverMutation = (options?: Partial<Options<DeleteRenderCoverData>>): UseMutationOptions<DeleteRenderCoverResponse, DeleteRenderCoverError, Options<DeleteRenderCoverData>> => {
    const mutationOptions: UseMutationOptions<DeleteRenderCoverResponse, DeleteRenderCoverError, Options<DeleteRenderCoverData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRenderCover({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Set Render Cover
 *
 * The Reel cover (Zernio instagramThumbnail): a JPEG, ideally 1080x1920 (the Editor sends exactly that).
 * Stored under a new name each time, so browsers never show a stale cover. 409 once the render has posts.
 */
export const setRenderCoverMutation = (options?: Partial<Options<SetRenderCoverData>>): UseMutationOptions<SetRenderCoverResponse, SetRenderCoverError, Options<SetRenderCoverData>> => {
    const mutationOptions: UseMutationOptions<SetRenderCoverResponse, SetRenderCoverError, Options<SetRenderCoverData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await setRenderCover({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listAccountsQueryKey = (options?: Options<ListAccountsData>) => createQueryKey('listAccounts', options);

/**
 * List Accounts
 */
export const listAccountsOptions = (options?: Options<ListAccountsData>) => queryOptions<ListAccountsResponse, DefaultError, ListAccountsResponse, ReturnType<typeof listAccountsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAccounts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAccountsQueryKey(options)
});

/**
 * Sync Accounts
 *
 * Pull GET /v1/accounts from Zernio (read-only) and upsert Instagram accounts by zernio_account_id.
 */
export const syncAccountsMutation = (options?: Partial<Options<SyncAccountsData>>): UseMutationOptions<SyncAccountsResponse, DefaultError, Options<SyncAccountsData>> => {
    const mutationOptions: UseMutationOptions<SyncAccountsResponse, DefaultError, Options<SyncAccountsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await syncAccounts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Account
 */
export const updateAccountMutation = (options?: Partial<Options<UpdateAccountData>>): UseMutationOptions<UpdateAccountResponse, UpdateAccountError, Options<UpdateAccountData>> => {
    const mutationOptions: UseMutationOptions<UpdateAccountResponse, UpdateAccountError, Options<UpdateAccountData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateAccount({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const nextSlotQueryKey = (options: Options<NextSlotData>) => createQueryKey('nextSlot', options);

/**
 * Next Slot
 */
export const nextSlotOptions = (options: Options<NextSlotData>) => queryOptions<NextSlotResponse, NextSlotError, NextSlotResponse, ReturnType<typeof nextSlotQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await nextSlot({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: nextSlotQueryKey(options)
});

export const listPostsQueryKey = (options?: Options<ListPostsData>) => createQueryKey('listPosts', options);

/**
 * List Posts
 *
 * Sorted by scheduled_for. from/to filter on coalesce(published_at, scheduled_for).
 */
export const listPostsOptions = (options?: Options<ListPostsData>) => queryOptions<ListPostsResponse, ListPostsError, ListPostsResponse, ReturnType<typeof listPostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listPosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listPostsQueryKey(options)
});

/**
 * Create Post
 */
export const createPostMutation = (options?: Partial<Options<CreatePostData>>): UseMutationOptions<CreatePostResponse, CreatePostError, Options<CreatePostData>> => {
    const mutationOptions: UseMutationOptions<CreatePostResponse, CreatePostError, Options<CreatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPostQueryKey = (options: Options<GetPostData>) => createQueryKey('getPost', options);

/**
 * Get Post
 */
export const getPostOptions = (options: Options<GetPostData>) => queryOptions<GetPostResponse, GetPostError, GetPostResponse, ReturnType<typeof getPostQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostQueryKey(options)
});

/**
 * Update Post
 */
export const updatePostMutation = (options?: Partial<Options<UpdatePostData>>): UseMutationOptions<UpdatePostResponse, UpdatePostError, Options<UpdatePostData>> => {
    const mutationOptions: UseMutationOptions<UpdatePostResponse, UpdatePostError, Options<UpdatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Auto Schedule
 */
export const autoScheduleMutation = (options?: Partial<Options<AutoScheduleData>>): UseMutationOptions<AutoScheduleResponse, AutoScheduleError, Options<AutoScheduleData>> => {
    const mutationOptions: UseMutationOptions<AutoScheduleResponse, AutoScheduleError, Options<AutoScheduleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await autoSchedule({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Approve Post
 */
export const approvePostMutation = (options?: Partial<Options<ApprovePostData>>): UseMutationOptions<ApprovePostResponse, ApprovePostError, Options<ApprovePostData>> => {
    const mutationOptions: UseMutationOptions<ApprovePostResponse, ApprovePostError, Options<ApprovePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await approvePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Cancel Post
 */
export const cancelPostMutation = (options?: Partial<Options<CancelPostData>>): UseMutationOptions<CancelPostResponse, CancelPostError, Options<CancelPostData>> => {
    const mutationOptions: UseMutationOptions<CancelPostResponse, CancelPostError, Options<CancelPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancelPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remedy Post
 *
 * FAILED / DEAD_LETTER only (409 {"code": "STATE_CONFLICT"} otherwise). See docs/PLAN.md section 4.
 */
export const remedyPostMutation = (options?: Partial<Options<RemedyPostData>>): UseMutationOptions<RemedyPostResponse, RemedyPostError, Options<RemedyPostData>> => {
    const mutationOptions: UseMutationOptions<RemedyPostResponse, RemedyPostError, Options<RemedyPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await remedyPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Health
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse, DefaultError, HealthResponse, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});

export const statusQueryKey = (options?: Options<StatusData>) => createQueryKey('status', options);

/**
 * Status
 */
export const statusOptions = (options?: Options<StatusData>) => queryOptions<StatusResponse, DefaultError, StatusResponse, ReturnType<typeof statusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await status({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: statusQueryKey(options)
});
